# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
# Distinguishes this project for local CLI; remote ref is nxzjttciafqaqevquuev.
project_id = "tanlabs-english-for-se"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
