export const brand = {
  coral800: '#9F2F2F',
  navy950: '#08122E',
  navy900: '#0D1E46',
  navy800: '#152A5C',
  navy700: '#1E3A7A',
  navy600: '#2A4A8A',
  navy500: '#3D4F73',
  coral700: '#B83838',
  coral600: '#D64545',
  coral500: '#E85A4F',
  coral400: '#F08070',
  coral300: '#F5A59A',
  cream50: '#FFF8F0',
  cream100: '#F5EDE4',
  cream200: '#E8DDD2',
  peach100: '#F0E0C0',
  peach50: '#FFF7F5',
  gray50: '#F7F7F8',
  gray100: '#EEEFF1',
  gray200: '#D8DAE0',
  gray300: '#B0B4BF',
  gray400: '#858B99',
  gray500: '#5C6373',
  gray600: '#3D424F',
  ink: '#0D1E46',
  paper: '#F5F6FA',
  fog: '#A9B3C9',
  chalk: '#F7F8FC',
  muted: '#5C667A',
  success: '#4CAF82',
  successSoft: '#E6F5ED',
  warning: '#E8A838',
  warningSoft: '#FFF4E0',
  errorSoft: '#FDECEC',
  red500: '#E05252',
  borderSubtle: '#EEEFF1',
  borderDefault: '#E2E6EF',
  borderDark: '#2A3F6E',
} as const;

/** Semantic colors aligned with Figma V2 Semantic/Color (Light). */
export const lightColors = {
  background: brand.paper,
  backgroundElevated: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceSecondary: brand.peach50,
  surfaceCard: '#FFFFFF',
  border: brand.borderDefault,
  borderSubtle: brand.borderSubtle,
  borderStrong: brand.gray300,
  text: brand.ink,
  textMuted: brand.muted,
  textSecondary: brand.muted,
  textInverse: '#FFFFFF',
  textOnDark: brand.chalk,
  primary: brand.coral700,
  primaryPressed: brand.coral800,
  primaryHover: brand.coral600,
  onPrimary: '#FFFFFF',
  primarySoft: brand.peach50,
  danger: brand.coral700,
  onDanger: '#FFFFFF',
  dangerSoft: brand.errorSoft,
  success: brand.success,
  successSoft: brand.successSoft,
  onSuccess: '#FFFFFF',
  warning: brand.warning,
  warningSoft: brand.warningSoft,
} as const;

/** Semantic colors aligned with Figma V2 Semantic/Color (Dark). */
export const darkColors = {
  background: brand.navy900,
  backgroundElevated: brand.navy800,
  surface: brand.navy800,
  surfaceSecondary: brand.navy700,
  surfaceCard: brand.navy800,
  border: brand.borderDark,
  borderSubtle: brand.navy700,
  borderStrong: brand.navy600,
  text: brand.chalk,
  textMuted: brand.fog,
  textSecondary: brand.fog,
  textInverse: brand.navy900,
  textOnDark: brand.chalk,
  primary: brand.coral400,
  primaryPressed: brand.coral500,
  primaryHover: brand.coral500,
  onPrimary: brand.navy900,
  primarySoft: brand.navy700,
  danger: brand.coral300,
  onDanger: brand.navy900,
  dangerSoft: brand.navy700,
  success: brand.success,
  successSoft: brand.navy700,
  onSuccess: brand.navy900,
  warning: brand.warning,
  warningSoft: brand.navy700,
} as const;

export type AppColors = {
  [K in keyof typeof lightColors]: string;
};
