/**
 * Generated by `pnpm run db:types` (Supabase CLI).
 * Do not hand-edit table shapes; regenerate after migrations.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.15';
  };
  public: {
    Tables: {
      app_config: {
        Row: {
          key: string;
          updated_at: string;
          value: Json;
        };
        Insert: {
          key: string;
          updated_at?: string;
          value: Json;
        };
        Update: {
          key?: string;
          updated_at?: string;
          value?: Json;
        };
        Relationships: [];
      };
      grammar_attempts: {
        Row: {
          answers: Json;
          client_attempt_id: string;
          completed_at: string;
          content_revision: number;
          correct_count: number;
          created_at: string;
          id: string;
          lesson_id: string;
          score: number;
          started_at: string;
          topic_id: string;
          total_count: number;
          user_id: string;
        };
        Insert: {
          answers: Json;
          client_attempt_id: string;
          completed_at: string;
          content_revision: number;
          correct_count: number;
          created_at?: string;
          id?: string;
          lesson_id: string;
          score: number;
          started_at: string;
          topic_id: string;
          total_count: number;
          user_id: string;
        };
        Update: {
          answers?: Json;
          client_attempt_id?: string;
          completed_at?: string;
          content_revision?: number;
          correct_count?: number;
          created_at?: string;
          id?: string;
          lesson_id?: string;
          score?: number;
          started_at?: string;
          topic_id?: string;
          total_count?: number;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'grammar_attempts_lesson_id_fkey';
            columns: ['lesson_id'];
            isOneToOne: false;
            referencedRelation: 'grammar_lessons';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'grammar_attempts_topic_id_fkey';
            columns: ['topic_id'];
            isOneToOne: false;
            referencedRelation: 'grammar_topics';
            referencedColumns: ['id'];
          },
        ];
      };
      grammar_exercises: {
        Row: {
          answer: Json;
          content_schema_version: number;
          created_at: string;
          exercise_key: string;
          explanation: string;
          id: string;
          lesson_id: string;
          payload: Json;
          prompt: string;
          published: boolean;
          sort_order: number;
          topic_id: string;
          type: string;
          updated_at: string;
        };
        Insert: {
          answer: Json;
          content_schema_version: number;
          created_at?: string;
          exercise_key: string;
          explanation: string;
          id?: string;
          lesson_id: string;
          payload: Json;
          prompt: string;
          published?: boolean;
          sort_order: number;
          topic_id: string;
          type: string;
          updated_at?: string;
        };
        Update: {
          answer?: Json;
          content_schema_version?: number;
          created_at?: string;
          exercise_key?: string;
          explanation?: string;
          id?: string;
          lesson_id?: string;
          payload?: Json;
          prompt?: string;
          published?: boolean;
          sort_order?: number;
          topic_id?: string;
          type?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'grammar_exercises_lesson_id_fkey';
            columns: ['lesson_id'];
            isOneToOne: false;
            referencedRelation: 'grammar_lessons';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'grammar_exercises_topic_id_fkey';
            columns: ['topic_id'];
            isOneToOne: false;
            referencedRelation: 'grammar_topics';
            referencedColumns: ['id'];
          },
        ];
      };
      grammar_lessons: {
        Row: {
          content: Json;
          content_revision: number;
          content_schema_version: number;
          created_at: string;
          id: string;
          level: string;
          published: boolean;
          slug: string;
          sort_order: number;
          title: string;
          description: string;
          topic_id: string;
          updated_at: string;
        };
        Insert: {
          content: Json;
          content_revision: number;
          content_schema_version: number;
          created_at?: string;
          description: string;
          id?: string;
          level: string;
          published?: boolean;
          slug: string;
          sort_order: number;
          title: string;
          topic_id: string;
          updated_at?: string;
        };
        Update: {
          content?: Json;
          content_revision?: number;
          content_schema_version?: number;
          created_at?: string;
          description?: string;
          id?: string;
          level?: string;
          published?: boolean;
          slug?: string;
          sort_order?: number;
          title?: string;
          topic_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'grammar_lessons_topic_id_fkey';
            columns: ['topic_id'];
            isOneToOne: false;
            referencedRelation: 'grammar_topics';
            referencedColumns: ['id'];
          },
        ];
      };
      grammar_topics: {
        Row: {
          category_slug: string;
          created_at: string;
          curriculum_version: number;
          description: string;
          id: string;
          is_optional: boolean;
          published: boolean;
          slug: string;
          sort_order: number;
          title: string;
          updated_at: string;
        };
        Insert: {
          category_slug?: string;
          created_at?: string;
          curriculum_version?: number;
          description: string;
          id?: string;
          is_optional?: boolean;
          published?: boolean;
          slug: string;
          sort_order: number;
          title: string;
          updated_at?: string;
        };
        Update: {
          category_slug?: string;
          created_at?: string;
          curriculum_version?: number;
          description?: string;
          id?: string;
          is_optional?: boolean;
          published?: boolean;
          slug?: string;
          sort_order?: number;
          title?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notification_settings: {
        Row: {
          enabled: boolean;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          enabled?: boolean;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          enabled?: boolean;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      practice_streaks: {
        Row: {
          celebrated_dates: string[];
          practice_dates: string[];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          celebrated_dates?: string[];
          practice_dates?: string[];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          celebrated_dates?: string[];
          practice_dates?: string[];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          created_at: string;
          display_name: string;
          english_level: string;
          id: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          display_name: string;
          english_level: string;
          id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          display_name?: string;
          english_level?: string;
          id?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_devices: {
        Row: {
          created_at: string;
          fcm_token: string;
          id: string;
          is_active: boolean;
          platform: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          fcm_token: string;
          id?: string;
          is_active?: boolean;
          platform: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          fcm_token?: string;
          id?: string;
          is_active?: boolean;
          platform?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      user_grammar_progress: {
        Row: {
          best_score: number;
          completed_at: string | null;
          created_at: string;
          id: string;
          last_activity_at: string | null;
          last_score: number;
          lesson_id: string;
          status: string;
          topic_id: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          best_score?: number;
          completed_at?: string | null;
          created_at?: string;
          id?: string;
          last_activity_at?: string | null;
          last_score?: number;
          lesson_id: string;
          status: string;
          topic_id: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          best_score?: number;
          completed_at?: string | null;
          created_at?: string;
          id?: string;
          last_activity_at?: string | null;
          last_score?: number;
          lesson_id?: string;
          status?: string;
          topic_id?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_grammar_progress_lesson_id_fkey';
            columns: ['lesson_id'];
            isOneToOne: false;
            referencedRelation: 'grammar_lessons';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'user_grammar_progress_topic_id_fkey';
            columns: ['topic_id'];
            isOneToOne: false;
            referencedRelation: 'grammar_topics';
            referencedColumns: ['id'];
          },
        ];
      };
      vocabulary_situations: {
        Row: {
          created_at: string;
          description: string;
          id: string;
          published: boolean;
          slug: string;
          sort_order: number;
          title: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          description: string;
          id?: string;
          published?: boolean;
          slug: string;
          sort_order: number;
          title: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          description?: string;
          id?: string;
          published?: boolean;
          slug?: string;
          sort_order?: number;
          title?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      vocabulary_items: {
        Row: {
          content: Json;
          content_revision: number;
          content_schema_version: number;
          context: string;
          core_order: number | null;
          countability: string | null;
          created_at: string;
          id: string;
          is_core: boolean;
          item_key: string;
          level: string;
          library_rank: number;
          meaning: string;
          pos: string | null;
          pronunciation: string | null;
          published: boolean;
          situation_id: string;
          sort_order: number;
          term: string;
          type: string;
          updated_at: string;
        };
        Insert: {
          content?: Json;
          content_revision: number;
          content_schema_version: number;
          context: string;
          core_order?: number | null;
          countability?: string | null;
          created_at?: string;
          id?: string;
          is_core?: boolean;
          item_key: string;
          level: string;
          library_rank?: number;
          meaning: string;
          pos?: string | null;
          pronunciation?: string | null;
          published?: boolean;
          situation_id: string;
          sort_order: number;
          term: string;
          type: string;
          updated_at?: string;
        };
        Update: {
          content?: Json;
          content_revision?: number;
          content_schema_version?: number;
          context?: string;
          core_order?: number | null;
          countability?: string | null;
          created_at?: string;
          id?: string;
          is_core?: boolean;
          item_key?: string;
          level?: string;
          library_rank?: number;
          meaning?: string;
          pos?: string | null;
          pronunciation?: string | null;
          published?: boolean;
          situation_id?: string;
          sort_order?: number;
          term?: string;
          type?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'vocabulary_items_situation_id_fkey';
            columns: ['situation_id'];
            isOneToOne: false;
            referencedRelation: 'vocabulary_situations';
            referencedColumns: ['id'];
          },
        ];
      };
      vocabulary_exercises: {
        Row: {
          content_schema_version: number;
          created_at: string;
          exercise_key: string;
          feedback: Json;
          id: string;
          item_id: string | null;
          payload: Json;
          prompt: string;
          published: boolean;
          situation_id: string;
          sort_order: number;
          type: string;
          updated_at: string;
        };
        Insert: {
          content_schema_version: number;
          created_at?: string;
          exercise_key: string;
          feedback: Json;
          id?: string;
          item_id?: string | null;
          payload: Json;
          prompt: string;
          published?: boolean;
          situation_id: string;
          sort_order: number;
          type: string;
          updated_at?: string;
        };
        Update: {
          content_schema_version?: number;
          created_at?: string;
          exercise_key?: string;
          feedback?: Json;
          id?: string;
          item_id?: string | null;
          payload?: Json;
          prompt?: string;
          published?: boolean;
          situation_id?: string;
          sort_order?: number;
          type?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'vocabulary_exercises_item_id_fkey';
            columns: ['item_id'];
            isOneToOne: false;
            referencedRelation: 'vocabulary_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'vocabulary_exercises_situation_id_fkey';
            columns: ['situation_id'];
            isOneToOne: false;
            referencedRelation: 'vocabulary_situations';
            referencedColumns: ['id'];
          },
        ];
      };
      user_vocabulary_progress: {
        Row: {
          correct_count: number;
          created_at: string;
          id: string;
          incorrect_count: number;
          item_id: string;
          last_result: boolean | null;
          last_seen_at: string | null;
          situation_id: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          correct_count?: number;
          created_at?: string;
          id?: string;
          incorrect_count?: number;
          item_id: string;
          last_result?: boolean | null;
          last_seen_at?: string | null;
          situation_id: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          correct_count?: number;
          created_at?: string;
          id?: string;
          incorrect_count?: number;
          item_id?: string;
          last_result?: boolean | null;
          last_seen_at?: string | null;
          situation_id?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_vocabulary_progress_item_id_fkey';
            columns: ['item_id'];
            isOneToOne: false;
            referencedRelation: 'vocabulary_items';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'user_vocabulary_progress_situation_id_fkey';
            columns: ['situation_id'];
            isOneToOne: false;
            referencedRelation: 'vocabulary_situations';
            referencedColumns: ['id'];
          },
        ];
      };
      vocabulary_attempts: {
        Row: {
          client_attempt_id: string;
          completed_at: string;
          content_revision: number;
          correct_count: number;
          created_at: string;
          id: string;
          item_results: Json;
          score: number;
          situation_id: string;
          started_at: string;
          total_count: number;
          user_id: string;
        };
        Insert: {
          client_attempt_id: string;
          completed_at: string;
          content_revision: number;
          correct_count: number;
          created_at?: string;
          id?: string;
          item_results: Json;
          score: number;
          situation_id: string;
          started_at: string;
          total_count: number;
          user_id: string;
        };
        Update: {
          client_attempt_id?: string;
          completed_at?: string;
          content_revision?: number;
          correct_count?: number;
          created_at?: string;
          id?: string;
          item_results?: Json;
          score?: number;
          situation_id?: string;
          started_at?: string;
          total_count?: number;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'vocabulary_attempts_situation_id_fkey';
            columns: ['situation_id'];
            isOneToOne: false;
            referencedRelation: 'vocabulary_situations';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      claim_device_token: {
        Args: { p_platform: string; p_token: string };
        Returns: undefined;
      };
      complete_grammar_attempt: {
        Args: {
          p_answers: Json;
          p_client_attempt_id: string;
          p_completed_at: string;
          p_content_revision: number;
          p_correct_count: number;
          p_lesson_id: string;
          p_score: number;
          p_started_at: string;
          p_topic_id: string;
          p_total_count: number;
        };
        Returns: {
          answers: Json;
          client_attempt_id: string;
          completed_at: string;
          content_revision: number;
          correct_count: number;
          created_at: string;
          id: string;
          lesson_id: string;
          score: number;
          started_at: string;
          topic_id: string;
          total_count: number;
          user_id: string;
        };
        SetofOptions: {
          from: '*';
          to: 'grammar_attempts';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      complete_vocabulary_attempt: {
        Args: {
          p_client_attempt_id: string;
          p_completed_at: string;
          p_content_revision: number;
          p_correct_count: number;
          p_item_results: Json;
          p_score: number;
          p_situation_id: string;
          p_started_at: string;
          p_total_count: number;
        };
        Returns: {
          client_attempt_id: string;
          completed_at: string;
          content_revision: number;
          correct_count: number;
          created_at: string;
          id: string;
          item_results: Json;
          score: number;
          situation_id: string;
          started_at: string;
          total_count: number;
          user_id: string;
        };
        SetofOptions: {
          from: '*';
          to: 'vocabulary_attempts';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      get_practice_streak: {
        Args: Record<PropertyKey, never>;
        Returns: {
          celebrated_dates: string[];
          practice_dates: string[];
          updated_at: string;
          user_id: string;
        };
        SetofOptions: {
          from: '*';
          to: 'practice_streaks';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      merge_practice_streak: {
        Args: {
          p_celebrated_dates: string[];
          p_practice_dates: string[];
        };
        Returns: {
          celebrated_dates: string[];
          practice_dates: string[];
          updated_at: string;
          user_id: string;
        };
        SetofOptions: {
          from: '*';
          to: 'practice_streaks';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
  ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R;
    }
    ? R
    : never
  : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
  ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I;
    }
    ? I
    : never
  : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
  ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U;
    }
    ? U
    : never
  : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
  ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
  : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
  ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
  : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;

/** Profile English levels allowed by RLS/check constraint. */
export type EnglishLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1';
export type Profile = Database['public']['Tables']['profiles']['Row'];
