#!/usr/bin/env bash
# Generate Supabase TypeScript types into src/types/database.ts
#
# Order:
# 1) --project-id + SUPABASE_ACCESS_TOKEN (no Docker; preferred for hosted)
# 2) --linked (after `supabase link`)
# 3) --db-url from .env.rls (may require Docker / older CLI)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/src/types/database.ts"
# Pin: latest often needs Docker for --db-url; Management API works with access token.
CLI_VERSION="${SUPABASE_CLI_VERSION:-2.113.0}"
PROJECT_REF="${SUPABASE_PROJECT_REF:-nxzjttciafqaqevquuev}"

if ! command -v npx >/dev/null 2>&1; then
  echo "npx is required" >&2
  exit 1
fi

if [[ -f "$ROOT/.env.rls" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env.rls"
  set +a
fi

DB_URL="${DATABASE_URL:-${SUPABASE_DB_URL:-}}"
ACCESS_TOKEN="${SUPABASE_ACCESS_TOKEN:-}"

HEADER=$(cat <<'EOF'
/**
 * Generated by `npm run db:types` (Supabase CLI).
 * Do not hand-edit table shapes; regenerate after migrations.
 */
EOF
)

TMP="$(mktemp)"
ERR="$(mktemp)"
cleanup() {
  rm -f "$TMP" "$ERR"
}
trap cleanup EXIT

run_gen() {
  # stdout = types; stderr = diagnostics
  if npx "supabase@${CLI_VERSION}" gen types typescript "$@" >"$TMP" 2>"$ERR"; then
    # CLI sometimes prints JSON errors to stdout with exit 0 — reject those.
    if head -c 1 "$TMP" | grep -q '{'; then
      return 1
    fi
    if ! grep -q 'export type Database' "$TMP"; then
      return 1
    fi
    return 0
  fi
  return 1
}

gen_ok=0
mode=""

if [[ -n "$ACCESS_TOKEN" ]]; then
  export SUPABASE_ACCESS_TOKEN="$ACCESS_TOKEN"
  if run_gen --project-id "$PROJECT_REF" --schema public; then
    gen_ok=1
    mode="project-id"
  fi
fi

if [[ "$gen_ok" -ne 1 ]]; then
  if run_gen --linked --schema public; then
    gen_ok=1
    mode="linked"
  fi
fi

if [[ "$gen_ok" -ne 1 && -n "$DB_URL" ]]; then
  echo "Note: --db-url typegen requires Docker; trying anyway…" >&2
  if run_gen --db-url "$DB_URL" --schema public; then
    gen_ok=1
    mode="db-url"
  fi
fi

if [[ "$gen_ok" -ne 1 ]]; then
  echo "Type generation failed." >&2
  echo "" >&2
  echo "Preferred (no Docker): add a personal access token to .env.rls:" >&2
  echo "  1. Create token: https://supabase.com/dashboard/account/tokens" >&2
  echo "  2. Add: SUPABASE_ACCESS_TOKEN=sbp_..." >&2
  echo "  3. Re-run: npm run db:types" >&2
  echo "" >&2
  echo "Or link the CLI:" >&2
  echo "  npx supabase@${CLI_VERSION} login --token <access-token>" >&2
  echo "  npx supabase@${CLI_VERSION} link --project-ref ${PROJECT_REF} -p <db-password>" >&2
  echo "  npm run db:types" >&2
  echo "" >&2
  echo "Falling back: keeping existing $OUT." >&2
  # Never dump secrets; strip connection strings from stderr.
  sed -E 's/(postgres|postgresql):\/\/[^[:space:]@]+@/\1:\/\/***@/g' "$ERR" >&2 || true
  exit 1
fi

{
  echo "$HEADER"
  echo
  cat "$TMP"
  cat <<'EOF'

/** Profile English levels allowed by RLS/check constraint. */
export type EnglishLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1';
export type Profile = Database['public']['Tables']['profiles']['Row'];
EOF
} >"$OUT"

echo "Wrote $OUT (via $mode)"
