begin;

-- Grammar seed generated from src/features/grammar/data/seedInventory.ts

delete from public.grammar_attempts;

delete from public.user_grammar_progress;

delete from public.grammar_exercises;

delete from public.grammar_lessons;

delete from public.grammar_topics;

insert into public.grammar_topics (id, slug, title, description, level, sort_order, published)
values ('a1000000-0000-4000-8000-000000000001', 'present-simple', 'Present Simple', 'Habits, facts, and recurring standup updates.', 'A2', 1, true)
on conflict (slug) do update set title = excluded.title, description = excluded.description, level = excluded.level, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_topics (id, slug, title, description, level, sort_order, published)
values ('a1000000-0000-4000-8000-000000000002', 'present-continuous', 'Present Continuous', 'Work in progress right now or around now.', 'A2', 2, true)
on conflict (slug) do update set title = excluded.title, description = excluded.description, level = excluded.level, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_topics (id, slug, title, description, level, sort_order, published)
values ('a1000000-0000-4000-8000-000000000003', 'past-simple', 'Past Simple', 'Finished work, incidents, and shipped changes.', 'A2', 3, true)
on conflict (slug) do update set title = excluded.title, description = excluded.description, level = excluded.level, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_topics (id, slug, title, description, level, sort_order, published)
values ('a1000000-0000-4000-8000-000000000004', 'present-perfect', 'Present Perfect', 'Experience and unfinished time windows at work.', 'B1', 4, true)
on conflict (slug) do update set title = excluded.title, description = excluded.description, level = excluded.level, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_topics (id, slug, title, description, level, sort_order, published)
values ('a1000000-0000-4000-8000-000000000005', 'future-forms', 'Future Forms', 'Plans with be going to and decisions with will.', 'B1', 5, true)
on conflict (slug) do update set title = excluded.title, description = excluded.description, level = excluded.level, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_lessons (id, topic_id, slug, summary, content, content_schema_version, content_revision, sort_order, published)
values ('a2000000-0000-4000-8000-000000000001', 'a1000000-0000-4000-8000-000000000001', 'present-simple-core', 'Use Present Simple for routines, facts, and recurring team habits.', '{"usage":"Choose Present Simple when the action is a habit, a fact, or a scheduled cascade that repeats.","forms":{"affirmative":"Subject + base verb (+s/es for he/she/it)","negative":"Subject + do/does not + base verb","question":"Do/Does + subject + base verb?"},"examples":[{"id":"ps-e1","context":"Standup","sentence":"I update the board every morning."},{"id":"ps-e2","context":"On-call","sentence":"She owns the alerts for checkout."},{"id":"ps-e3","context":"CI","sentence":"The pipeline runs on every pull request."},{"id":"ps-e4","context":"Meetings","sentence":"We review incidents on Mondays."},{"id":"ps-e5","context":"Clients","sentence":"The API returns pagination headers."},{"id":"ps-e6","context":"Testing","sentence":"He writes smoke tests for releases."}],"tips":["Use does not / doesn’t with he/she/it.","Keep workplace subjects concrete: I, we, the service, the pipeline."]}'::jsonb, 1, 1, 1, true)
on conflict (topic_id, slug) do update set summary = excluded.summary, content = excluded.content, content_schema_version = excluded.content_schema_version, content_revision = excluded.content_revision, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_lessons (id, topic_id, slug, summary, content, content_schema_version, content_revision, sort_order, published)
values ('a2000000-0000-4000-8000-000000000002', 'a1000000-0000-4000-8000-000000000002', 'present-continuous-core', 'Use Present Continuous for work happening now or temporary focus.', '{"usage":"Choose Present Continuous for actions in progress around now, temporary spikes, or current investigations.","forms":{"affirmative":"Subject + am/is/are + verb-ing","negative":"Subject + am/is/are not + verb-ing","question":"Am/Is/Are + subject + verb-ing?"},"examples":[{"id":"pc-e1","context":"Debugging","sentence":"I am tracing the 500s in auth."},{"id":"pc-e2","context":"Deploy","sentence":"We are rolling out the canary now."},{"id":"pc-e3","context":"Review","sentence":"She is reviewing the migration PR."},{"id":"pc-e4","context":"Incident","sentence":"They are stabilizing the queue."},{"id":"pc-e5","context":"Standup","sentence":"He is pairing on the flaky test."},{"id":"pc-e6","context":"Client","sentence":"The vendor is updating their schema."}],"tips":["Prefer continuous for temporary work, not permanent responsibilities."]}'::jsonb, 1, 1, 1, true)
on conflict (topic_id, slug) do update set summary = excluded.summary, content = excluded.content, content_schema_version = excluded.content_schema_version, content_revision = excluded.content_revision, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_lessons (id, topic_id, slug, summary, content, content_schema_version, content_revision, sort_order, published)
values ('a2000000-0000-4000-8000-000000000003', 'a1000000-0000-4000-8000-000000000003', 'past-simple-core', 'Use Past Simple for finished actions with a clear time in the past.', '{"usage":"Choose Past Simple when the change, outage, or decision is finished and the time is known or implied.","forms":{"affirmative":"Subject + past verb","negative":"Subject + did not + base verb","question":"Did + subject + base verb?"},"examples":[{"id":"past-e1","context":"Ship","sentence":"We shipped the fix yesterday."},{"id":"past-e2","context":"Incident","sentence":"The database failed at 09:12."},{"id":"past-e3","context":"Meeting","sentence":"I raised the risk in standup."},{"id":"past-e4","context":"Review","sentence":"She approved the schema change."},{"id":"past-e5","context":"Client","sentence":"They asked for a rollback window."},{"id":"past-e6","context":"Testing","sentence":"He caught the regression in QA."}],"tips":["Do not mix present perfect when a finished past time is stated."]}'::jsonb, 1, 1, 1, true)
on conflict (topic_id, slug) do update set summary = excluded.summary, content = excluded.content, content_schema_version = excluded.content_schema_version, content_revision = excluded.content_revision, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_lessons (id, topic_id, slug, summary, content, content_schema_version, content_revision, sort_order, published)
values ('a2000000-0000-4000-8000-000000000004', 'a1000000-0000-4000-8000-000000000004', 'present-perfect-core', 'Use Present Perfect for experience and unfinished time at work.', '{"usage":"Choose Present Perfect for results that still matter now, or experience without a finished past time.","forms":{"affirmative":"Subject + have/has + past participle","negative":"Subject + have/has not + past participle","question":"Have/Has + subject + past participle?"},"examples":[{"id":"pp-e1","context":"Status","sentence":"I have finished the migration plan."},{"id":"pp-e2","context":"Experience","sentence":"She has debugged Kafka lag before."},{"id":"pp-e3","context":"Week","sentence":"We have closed three high sevs this week."},{"id":"pp-e4","context":"Blocker","sentence":"They have not answered the ticket yet."},{"id":"pp-e5","context":"Release","sentence":"Has the canary completed?"},{"id":"pp-e6","context":"Client","sentence":"The partner has shared the OpenAPI file."}],"tips":["Avoid Present Perfect with finished time phrases like yesterday."]}'::jsonb, 1, 1, 1, true)
on conflict (topic_id, slug) do update set summary = excluded.summary, content = excluded.content, content_schema_version = excluded.content_schema_version, content_revision = excluded.content_revision, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_lessons (id, topic_id, slug, summary, content, content_schema_version, content_revision, sort_order, published)
values ('a2000000-0000-4000-8000-000000000005', 'a1000000-0000-4000-8000-000000000005', 'future-forms-core', 'Use be going to for plans and will for decisions or offers.', '{"usage":"Future Forms in PH2 cover only will and be going to — not other futures.","forms":{"affirmative":"Subject + will + base · Subject + am/is/are going to + base","negative":"Subject + will not + base · Subject + am/is/are not going to + base","question":"Will + subject + base? · Am/Is/Are + subject + going to + base?"},"examples":[{"id":"ff-e1","context":"Plan","sentence":"We are going to freeze the branch tonight."},{"id":"ff-e2","context":"Offer","sentence":"I will pair on the flaky suite."},{"id":"ff-e3","context":"Decision","sentence":"Okay — we will roll back."},{"id":"ff-e4","context":"Plan","sentence":"She is going to open the RFC tomorrow."},{"id":"ff-e5","context":"Client","sentence":"They will send updated credentials."},{"id":"ff-e6","context":"Meeting","sentence":"I am going to demo the dashboard."}],"tips":["Use going to for prior plans; will for decisions made in the moment."]}'::jsonb, 1, 1, 1, true)
on conflict (topic_id, slug) do update set summary = excluded.summary, content = excluded.content, content_schema_version = excluded.content_schema_version, content_revision = excluded.content_revision, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000001', 'a1000000-0000-4000-8000-000000000001', 'a2000000-0000-4000-8000-000000000001', 'ps-x1', 'multiple_choice', 'Choose the best standup update.', '{"options":[{"id":"a","label":"I update the board every morning."},{"id":"b","label":"I am update the board every morning."},{"id":"c","label":"I updating the board every morning."},{"id":"d","label":"I have update the board every morning."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Habits use Present Simple.', 1, 1, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000002', 'a1000000-0000-4000-8000-000000000001', 'a2000000-0000-4000-8000-000000000001', 'ps-x2', 'fill_blank', 'Complete the sentence about ownership.', '{"template":"She ___ the alerts for checkout."}'::jsonb, '{"accepted":["owns","Owns"]}'::jsonb, 'Third-person singular needs -s.', 1, 2, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000003', 'a1000000-0000-4000-8000-000000000001', 'a2000000-0000-4000-8000-000000000001', 'ps-x3', 'sentence_order', 'Order this CI fact.', '{"tokens":[{"id":"t1","text":"The"},{"id":"t2","text":"pipeline"},{"id":"t3","text":"runs"},{"id":"t4","text":"on"},{"id":"t5","text":"every"},{"id":"t6","text":"pull"},{"id":"t7","text":"request."}]}'::jsonb, '{"tokenIds":["t1","t2","t3","t4","t5","t6","t7"]}'::jsonb, 'Facts about systems use Present Simple.', 1, 3, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000004', 'a1000000-0000-4000-8000-000000000001', 'a2000000-0000-4000-8000-000000000001', 'ps-x4', 'multiple_choice', 'Which negative is correct?', '{"options":[{"id":"a","label":"He doesn’t run the nightly job."},{"id":"b","label":"He don’t run the nightly job."},{"id":"c","label":"He not runs the nightly job."},{"id":"d","label":"He isn’t run the nightly job."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Use doesn’t + base verb with he/she/it.', 1, 4, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000005', 'a1000000-0000-4000-8000-000000000001', 'a2000000-0000-4000-8000-000000000001', 'ps-x5', 'fill_blank', 'Fill the blank for a recurring review.', '{"template":"We ___ incidents on Mondays."}'::jsonb, '{"accepted":["review","Review"]}'::jsonb, 'Plural we + base verb.', 1, 5, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000006', 'a1000000-0000-4000-8000-000000000001', 'a2000000-0000-4000-8000-000000000001', 'ps-x6', 'multiple_choice', 'Pick the workplace fact.', '{"options":[{"id":"a","label":"The API returns pagination headers."},{"id":"b","label":"The API is return pagination headers."},{"id":"c","label":"The API returning pagination headers."},{"id":"d","label":"The API will returning pagination headers."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'System facts use Present Simple.', 1, 6, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000007', 'a1000000-0000-4000-8000-000000000001', 'a2000000-0000-4000-8000-000000000001', 'ps-x7', 'fill_blank', 'Complete the QA habit.', '{"template":"He ___ smoke tests for releases."}'::jsonb, '{"accepted":["writes","Writes"]}'::jsonb, 'He/she/it → writes.', 1, 7, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000008', 'a1000000-0000-4000-8000-000000000001', 'a2000000-0000-4000-8000-000000000001', 'ps-x8', 'multiple_choice', 'Choose the question form.', '{"options":[{"id":"a","label":"Does the job fail on bad input?"},{"id":"b","label":"Do the job fails on bad input?"},{"id":"c","label":"Is the job fails on bad input?"},{"id":"d","label":"Does the job fails on bad input?"}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Does + subject + base verb.', 1, 8, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000009', 'a1000000-0000-4000-8000-000000000002', 'a2000000-0000-4000-8000-000000000002', 'pc-x1', 'multiple_choice', 'Choose the best debugging update.', '{"options":[{"id":"a","label":"I am tracing the 500s in auth."},{"id":"b","label":"I trace the 500s in auth right now always."},{"id":"c","label":"I tracing the 500s in auth."},{"id":"d","label":"I will tracing the 500s in auth."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Current investigation → continuous.', 1, 1, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000010', 'a1000000-0000-4000-8000-000000000002', 'a2000000-0000-4000-8000-000000000002', 'pc-x2', 'fill_blank', 'Complete the deploy update.', '{"template":"We ___ rolling out the canary now."}'::jsonb, '{"accepted":["are","Are"]}'::jsonb, 'We + are + verb-ing.', 1, 2, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000011', 'a1000000-0000-4000-8000-000000000002', 'a2000000-0000-4000-8000-000000000002', 'pc-x3', 'sentence_order', 'Order this review update.', '{"tokens":[{"id":"t1","text":"She"},{"id":"t2","text":"is"},{"id":"t3","text":"reviewing"},{"id":"t4","text":"the"},{"id":"t5","text":"migration"},{"id":"t6","text":"PR."}]}'::jsonb, '{"tokenIds":["t1","t2","t3","t4","t5","t6"]}'::jsonb, 'Temporary review work uses continuous.', 1, 3, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000012', 'a1000000-0000-4000-8000-000000000002', 'a2000000-0000-4000-8000-000000000002', 'pc-x4', 'multiple_choice', 'Which sentence is in progress now?', '{"options":[{"id":"a","label":"They are stabilizing the queue."},{"id":"b","label":"They stabilize the queue every year forever."},{"id":"c","label":"They stabilized the queue tomorrow."},{"id":"d","label":"They will stabilized the queue."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Stabilizing now → continuous.', 1, 4, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000013', 'a1000000-0000-4000-8000-000000000002', 'a2000000-0000-4000-8000-000000000002', 'pc-x5', 'fill_blank', 'Fill the blank.', '{"template":"He is ___ on the flaky test."}'::jsonb, '{"accepted":["pairing","Pairing"]}'::jsonb, 'am/is/are + verb-ing.', 1, 5, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000014', 'a1000000-0000-4000-8000-000000000002', 'a2000000-0000-4000-8000-000000000002', 'pc-x6', 'multiple_choice', 'Pick the vendor update.', '{"options":[{"id":"a","label":"The vendor is updating their schema."},{"id":"b","label":"The vendor update their schema nowing."},{"id":"c","label":"The vendor are update their schema."},{"id":"d","label":"The vendor will updating their schema yesterday."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Temporary vendor work → continuous.', 1, 6, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000015', 'a1000000-0000-4000-8000-000000000002', 'a2000000-0000-4000-8000-000000000002', 'pc-x7', 'fill_blank', 'Complete the negative.', '{"template":"I ___ not changing production tonight."}'::jsonb, '{"accepted":["am","Am"]}'::jsonb, 'I + am not + verb-ing.', 1, 7, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000016', 'a1000000-0000-4000-8000-000000000002', 'a2000000-0000-4000-8000-000000000002', 'pc-x8', 'multiple_choice', 'Choose the question.', '{"options":[{"id":"a","label":"Are you blocking on the API dependency?"},{"id":"b","label":"Do you blocking on the API dependency?"},{"id":"c","label":"Are you block on the API dependency?"},{"id":"d","label":"Is you blocking on the API dependency?"}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Are + you + verb-ing?', 1, 8, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000017', 'a1000000-0000-4000-8000-000000000003', 'a2000000-0000-4000-8000-000000000003', 'past-x1', 'multiple_choice', 'Choose the finished ship update.', '{"options":[{"id":"a","label":"We shipped the fix yesterday."},{"id":"b","label":"We have shipped the fix yesterday."},{"id":"c","label":"We are shipping the fix yesterday."},{"id":"d","label":"We ship the fix yesterday."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Finished past time → Past Simple.', 1, 1, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000018', 'a1000000-0000-4000-8000-000000000003', 'a2000000-0000-4000-8000-000000000003', 'past-x2', 'fill_blank', 'Complete the incident note.', '{"template":"The database ___ at 09:12."}'::jsonb, '{"accepted":["failed","Failed"]}'::jsonb, 'Finished past event → Past Simple.', 1, 2, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000019', 'a1000000-0000-4000-8000-000000000003', 'a2000000-0000-4000-8000-000000000003', 'past-x3', 'sentence_order', 'Order this standup note.', '{"tokens":[{"id":"t1","text":"I"},{"id":"t2","text":"raised"},{"id":"t3","text":"the"},{"id":"t4","text":"risk"},{"id":"t5","text":"in"},{"id":"t6","text":"standup."}]}'::jsonb, '{"tokenIds":["t1","t2","t3","t4","t5","t6"]}'::jsonb, 'Completed action in a past meeting → Past Simple.', 1, 3, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000020', 'a1000000-0000-4000-8000-000000000003', 'a2000000-0000-4000-8000-000000000003', 'past-x4', 'multiple_choice', 'Which negative is correct?', '{"options":[{"id":"a","label":"She did not approve the risky change."},{"id":"b","label":"She did not approved the risky change."},{"id":"c","label":"She not approve the risky change."},{"id":"d","label":"She doesn’t approved the risky change yesterday."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'did not + base verb.', 1, 4, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000021', 'a1000000-0000-4000-8000-000000000003', 'a2000000-0000-4000-8000-000000000003', 'past-x5', 'fill_blank', 'Fill the blank.', '{"template":"They ___ for a rollback window."}'::jsonb, '{"accepted":["asked","Asked"]}'::jsonb, 'Past of ask → asked.', 1, 5, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000022', 'a1000000-0000-4000-8000-000000000003', 'a2000000-0000-4000-8000-000000000003', 'past-x6', 'multiple_choice', 'Pick the QA note.', '{"options":[{"id":"a","label":"He caught the regression in QA."},{"id":"b","label":"He has caught the regression yesterday."},{"id":"c","label":"He is catch the regression in QA."},{"id":"d","label":"He catch the regression in QA yesterday."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Finished QA find → Past Simple.', 1, 6, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000023', 'a1000000-0000-4000-8000-000000000003', 'a2000000-0000-4000-8000-000000000003', 'past-x7', 'fill_blank', 'Complete the review outcome.', '{"template":"She ___ the schema change."}'::jsonb, '{"accepted":["approved","Approved"]}'::jsonb, 'Past of approve.', 1, 7, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000024', 'a1000000-0000-4000-8000-000000000003', 'a2000000-0000-4000-8000-000000000003', 'past-x8', 'multiple_choice', 'Choose the question.', '{"options":[{"id":"a","label":"Did the canary finish before lunch?"},{"id":"b","label":"Did the canary finished before lunch?"},{"id":"c","label":"Does the canary finished before lunch?"},{"id":"d","label":"Have the canary finish before lunch yesterday?"}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Did + subject + base verb.', 1, 8, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000025', 'a1000000-0000-4000-8000-000000000004', 'a2000000-0000-4000-8000-000000000004', 'pp-x1', 'multiple_choice', 'Choose the status that still matters now.', '{"options":[{"id":"a","label":"I have finished the migration plan."},{"id":"b","label":"I finished the migration plan yesterday morning at 9."},{"id":"c","label":"I am finish the migration plan."},{"id":"d","label":"I finish the migration plan tomorrow."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Result relevant now → Present Perfect.', 1, 1, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000026', 'a1000000-0000-4000-8000-000000000004', 'a2000000-0000-4000-8000-000000000004', 'pp-x2', 'fill_blank', 'Complete the experience sentence.', '{"template":"She has ___ Kafka lag before."}'::jsonb, '{"accepted":["debugged","Debugged"]}'::jsonb, 'have/has + past participle.', 1, 2, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000027', 'a1000000-0000-4000-8000-000000000004', 'a2000000-0000-4000-8000-000000000004', 'pp-x3', 'sentence_order', 'Order this weekly summary.', '{"tokens":[{"id":"t1","text":"We"},{"id":"t2","text":"have"},{"id":"t3","text":"closed"},{"id":"t4","text":"three"},{"id":"t5","text":"high"},{"id":"t6","text":"sevs"},{"id":"t7","text":"this"},{"id":"t8","text":"week."}]}'::jsonb, '{"tokenIds":["t1","t2","t3","t4","t5","t6","t7","t8"]}'::jsonb, 'Unfinished time (this week) → Present Perfect.', 1, 3, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000028', 'a1000000-0000-4000-8000-000000000004', 'a2000000-0000-4000-8000-000000000004', 'pp-x4', 'multiple_choice', 'Which negative fits an open ticket?', '{"options":[{"id":"a","label":"They have not answered the ticket yet."},{"id":"b","label":"They did not answered the ticket yet."},{"id":"c","label":"They not have answer the ticket yet."},{"id":"d","label":"They hasn’t answer the ticket yesterday."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'have not + past participle + yet.', 1, 4, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000029', 'a1000000-0000-4000-8000-000000000004', 'a2000000-0000-4000-8000-000000000004', 'pp-x5', 'fill_blank', 'Fill the blank.', '{"template":"___ the canary completed?"}'::jsonb, '{"accepted":["Has","has"]}'::jsonb, 'Has + singular subject + past participle.', 1, 5, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000030', 'a1000000-0000-4000-8000-000000000004', 'a2000000-0000-4000-8000-000000000004', 'pp-x6', 'multiple_choice', 'Pick the partner update without a finished past time.', '{"options":[{"id":"a","label":"The partner has shared the OpenAPI file."},{"id":"b","label":"The partner shared the OpenAPI file yesterday at noon."},{"id":"c","label":"The partner sharing the OpenAPI file."},{"id":"d","label":"The partner will shared the OpenAPI file."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'No finished past time → Present Perfect is natural.', 1, 6, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000031', 'a1000000-0000-4000-8000-000000000004', 'a2000000-0000-4000-8000-000000000004', 'pp-x7', 'fill_blank', 'Complete the sentence.', '{"template":"I have ___ two release notes this sprint."}'::jsonb, '{"accepted":["written","Written"]}'::jsonb, 'have + past participle written.', 1, 7, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000032', 'a1000000-0000-4000-8000-000000000004', 'a2000000-0000-4000-8000-000000000004', 'pp-x8', 'multiple_choice', 'Choose the correct form.', '{"options":[{"id":"a","label":"Have you seen the new latency chart?"},{"id":"b","label":"Have you saw the new latency chart?"},{"id":"c","label":"Did you seen the new latency chart yet this week?"},{"id":"d","label":"Has you seen the new latency chart?"}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Have + subject + past participle.', 1, 8, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000033', 'a1000000-0000-4000-8000-000000000005', 'a2000000-0000-4000-8000-000000000005', 'ff-x1', 'multiple_choice', 'Choose the planned freeze.', '{"options":[{"id":"a","label":"We are going to freeze the branch tonight."},{"id":"b","label":"We will going to freeze the branch tonight."},{"id":"c","label":"We going freeze the branch tonight."},{"id":"d","label":"We are freeze the branch tonight."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Prior plan → be going to.', 1, 1, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000034', 'a1000000-0000-4000-8000-000000000005', 'a2000000-0000-4000-8000-000000000005', 'ff-x2', 'fill_blank', 'Complete the offer.', '{"template":"I ___ pair on the flaky suite."}'::jsonb, '{"accepted":["will","Will"]}'::jsonb, 'Offer/decision → will.', 1, 2, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000035', 'a1000000-0000-4000-8000-000000000005', 'a2000000-0000-4000-8000-000000000005', 'ff-x3', 'sentence_order', 'Order this decision.', '{"tokens":[{"id":"t1","text":"Okay"},{"id":"t2","text":"—"},{"id":"t3","text":"we"},{"id":"t4","text":"will"},{"id":"t5","text":"roll"},{"id":"t6","text":"back."}]}'::jsonb, '{"tokenIds":["t1","t2","t3","t4","t5","t6"]}'::jsonb, 'Decision made now → will.', 1, 3, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000036', 'a1000000-0000-4000-8000-000000000005', 'a2000000-0000-4000-8000-000000000005', 'ff-x4', 'multiple_choice', 'Which sentence is a prior plan?', '{"options":[{"id":"a","label":"She is going to open the RFC tomorrow."},{"id":"b","label":"She will opened the RFC tomorrow."},{"id":"c","label":"She going to opens the RFC tomorrow."},{"id":"d","label":"She is open the RFC tomorrow."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Planned future → be going to.', 1, 4, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000037', 'a1000000-0000-4000-8000-000000000005', 'a2000000-0000-4000-8000-000000000005', 'ff-x5', 'fill_blank', 'Fill the blank for a client promise.', '{"template":"They ___ send updated credentials."}'::jsonb, '{"accepted":["will","Will"]}'::jsonb, 'Promise/decision → will.', 1, 5, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000038', 'a1000000-0000-4000-8000-000000000005', 'a2000000-0000-4000-8000-000000000005', 'ff-x6', 'multiple_choice', 'Pick the demo plan.', '{"options":[{"id":"a","label":"I am going to demo the dashboard."},{"id":"b","label":"I will going demo the dashboard."},{"id":"c","label":"I am go to demo the dashboard."},{"id":"d","label":"I going demo the dashboard."}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Scheduled personal plan → be going to.', 1, 6, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000039', 'a1000000-0000-4000-8000-000000000005', 'a2000000-0000-4000-8000-000000000005', 'ff-x7', 'fill_blank', 'Complete the negative plan.', '{"template":"We are not ___ to cut the release this afternoon."}'::jsonb, '{"accepted":["going","Going"]}'::jsonb, 'be + not + going to.', 1, 7, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

insert into public.grammar_exercises (id, topic_id, lesson_id, exercise_key, type, prompt, payload, answer, explanation, content_schema_version, sort_order, published)
values ('a3000000-0000-4000-8000-000000000040', 'a1000000-0000-4000-8000-000000000005', 'a2000000-0000-4000-8000-000000000005', 'ff-x8', 'multiple_choice', 'Choose the question with will.', '{"options":[{"id":"a","label":"Will you join the war-room bridge?"},{"id":"b","label":"Will you joining the war-room bridge?"},{"id":"c","label":"Are you will join the war-room bridge?"},{"id":"d","label":"Will you to join the war-room bridge?"}]}'::jsonb, '{"optionId":"a"}'::jsonb, 'Will + subject + base verb.', 1, 8, true)
on conflict (lesson_id, exercise_key) do update set type = excluded.type, prompt = excluded.prompt, payload = excluded.payload, answer = excluded.answer, explanation = excluded.explanation, content_schema_version = excluded.content_schema_version, sort_order = excluded.sort_order, published = excluded.published, updated_at = now();

commit;
