begin;

-- Generated by `pnpm run vocabulary:core:sql` from core-expressions.json
-- Marks 50 core expressions. Does not rewrite the 2500-term library seed.

update public.vocabulary_items
set is_core = false, core_order = null
where is_core = true;

-- daily-standup #1 on track
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 1,
  pronunciation = 'on trak',
  countability = 'na',
  type = 'phrase',
  meaning = 'Progress matches the plan or the date you already shared.',
  context = 'Standup',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["We are on track for ...","Still on track if CI stays green"],"examples":[["Standup","We are on track for the Friday release."]],"alternatives":[],"notes":[],"pronunciation":"on trak","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'daily-standup'
  and lower(i.term) = lower('on track');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-on-track',
  'phrase',
  'on track',
  'Progress matches the plan or the date you already shared.',
  'Standup',
  'A2',
  'phr',
  '{"patterns":["We are on track for ...","Still on track if CI stays green"],"examples":[["Standup","We are on track for the Friday release."]],"alternatives":[],"notes":[],"pronunciation":"on trak","countability":"na"}'::jsonb,
  1,
  1,
  1,
  true,
  true,
  1,
  'on trak',
  'na'
from public.vocabulary_situations as s
where s.slug = 'daily-standup'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('on track')
  );

-- daily-standup #2 blocked on
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 2,
  pronunciation = 'blokt on',
  countability = 'na',
  type = 'phrase',
  meaning = 'Waiting on a person, access, or dependency before you can continue.',
  context = 'Standup',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["I am blocked on ...","Blocked on review / access / the API"],"examples":[["Standup","I am blocked on review for the auth PR."]],"alternatives":[],"notes":[],"pronunciation":"blokt on","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'daily-standup'
  and lower(i.term) = lower('blocked on');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-blocked-on',
  'phrase',
  'blocked on',
  'Waiting on a person, access, or dependency before you can continue.',
  'Standup',
  'A2',
  'phr',
  '{"patterns":["I am blocked on ...","Blocked on review / access / the API"],"examples":[["Standup","I am blocked on review for the auth PR."]],"alternatives":[],"notes":[],"pronunciation":"blokt on","countability":"na"}'::jsonb,
  1,
  1,
  2,
  true,
  true,
  2,
  'blokt on',
  'na'
from public.vocabulary_situations as s
where s.slug = 'daily-standup'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('blocked on')
  );

-- daily-standup #3 blocked by
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 3,
  pronunciation = 'blokt bai',
  countability = 'na',
  type = 'phrase',
  meaning = 'Name the dependency or person that is stopping progress.',
  context = 'Standup',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["I am blocked by ...","blocked by the API / review / access"],"examples":[["Standup","I am blocked by the API dependency."]],"alternatives":[],"notes":[],"pronunciation":"blokt bai","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'daily-standup'
  and lower(i.term) = lower('blocked by');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-blocked-by',
  'phrase',
  'blocked by',
  'Name the dependency or person that is stopping progress.',
  'Standup',
  'B1',
  'phr',
  '{"patterns":["I am blocked by ...","blocked by the API / review / access"],"examples":[["Standup","I am blocked by the API dependency."]],"alternatives":[],"notes":[],"pronunciation":"blokt bai","countability":"na"}'::jsonb,
  1,
  1,
  3,
  true,
  true,
  3,
  'blokt bai',
  'na'
from public.vocabulary_situations as s
where s.slug = 'daily-standup'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('blocked by')
  );

-- daily-standup #4 ETA is EOD
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 4,
  pronunciation = 'ee-tee-ei iz ee-oh-dee',
  countability = 'na',
  type = 'phrase',
  meaning = 'Share a finish time, usually with the condition that still gates it.',
  context = 'Standup',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["ETA is EOD if CI stays green","ETA is EOD"],"examples":[["Standup","ETA is EOD if CI stays green."]],"alternatives":[],"notes":[],"pronunciation":"ee-tee-ei iz ee-oh-dee","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'daily-standup'
  and lower(i.term) = lower('ETA is EOD');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-eta-is-eod',
  'phrase',
  'ETA is EOD',
  'Share a finish time, usually with the condition that still gates it.',
  'Standup',
  'B1',
  'phr',
  '{"patterns":["ETA is EOD if CI stays green","ETA is EOD"],"examples":[["Standup","ETA is EOD if CI stays green."]],"alternatives":[],"notes":[],"pronunciation":"ee-tee-ei iz ee-oh-dee","countability":"na"}'::jsonb,
  1,
  1,
  4,
  true,
  true,
  4,
  'ee-tee-ei iz ee-oh-dee',
  'na'
from public.vocabulary_situations as s
where s.slug = 'daily-standup'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('ETA is EOD')
  );

-- daily-standup #5 ETA slipped
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 5,
  pronunciation = 'ee-tee-ei slipt',
  countability = 'na',
  type = 'phrase',
  meaning = 'The promised finish time moved later.',
  context = 'Standup',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["The ETA slipped to ...","ETA slipped after the outage"],"examples":[["Standup","ETA slipped to tomorrow after the flaky tests."]],"alternatives":[],"notes":[],"pronunciation":"ee-tee-ei slipt","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'daily-standup'
  and lower(i.term) = lower('ETA slipped');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-eta-slipped',
  'phrase',
  'ETA slipped',
  'The promised finish time moved later.',
  'Standup',
  'B1',
  'phr',
  '{"patterns":["The ETA slipped to ...","ETA slipped after the outage"],"examples":[["Standup","ETA slipped to tomorrow after the flaky tests."]],"alternatives":[],"notes":[],"pronunciation":"ee-tee-ei slipt","countability":"na"}'::jsonb,
  1,
  1,
  5,
  true,
  true,
  5,
  'ee-tee-ei slipt',
  'na'
from public.vocabulary_situations as s
where s.slug = 'daily-standup'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('ETA slipped')
  );

-- daily-standup #6 owner assigned
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 6,
  pronunciation = 'oh-ner uh-saind',
  countability = 'na',
  type = 'phrase',
  meaning = 'Someone is already responsible for the ticket or follow-up.',
  context = 'Standup',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Owner assigned","Owner assigned to ..."],"examples":[["Standup","Owner assigned; I will post the rollback note."]],"alternatives":[],"notes":[],"pronunciation":"oh-ner uh-saind","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'daily-standup'
  and lower(i.term) = lower('owner assigned');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-owner-assigned',
  'phrase',
  'owner assigned',
  'Someone is already responsible for the ticket or follow-up.',
  'Standup',
  'A2',
  'phr',
  '{"patterns":["Owner assigned","Owner assigned to ..."],"examples":[["Standup","Owner assigned; I will post the rollback note."]],"alternatives":[],"notes":[],"pronunciation":"oh-ner uh-saind","countability":"na"}'::jsonb,
  1,
  1,
  6,
  true,
  true,
  6,
  'oh-ner uh-saind',
  'na'
from public.vocabulary_situations as s
where s.slug = 'daily-standup'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('owner assigned')
  );

-- daily-standup #7 follow up later
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 7,
  pronunciation = 'fol-oh up lei-ter',
  countability = 'na',
  type = 'phrase',
  meaning = 'Park the thread and return with an update after the meeting.',
  context = 'Standup',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Let''s follow up later","I will follow up later with ..."],"examples":[["Standup","Let''s follow up later with the API owner."]],"alternatives":[],"notes":[],"pronunciation":"fol-oh up lei-ter","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'daily-standup'
  and lower(i.term) = lower('follow up later');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-follow-up-later',
  'phrase',
  'follow up later',
  'Park the thread and return with an update after the meeting.',
  'Standup',
  'A2',
  'phr',
  '{"patterns":["Let''s follow up later","I will follow up later with ..."],"examples":[["Standup","Let''s follow up later with the API owner."]],"alternatives":[],"notes":[],"pronunciation":"fol-oh up lei-ter","countability":"na"}'::jsonb,
  1,
  1,
  7,
  true,
  true,
  7,
  'fol-oh up lei-ter',
  'na'
from public.vocabulary_situations as s
where s.slug = 'daily-standup'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('follow up later')
  );

-- daily-standup #8 action items open
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 8,
  pronunciation = 'ak-shun ai-temz',
  countability = 'na',
  type = 'phrase',
  meaning = 'Follow-ups from the meeting are still not done.',
  context = 'Standup',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Action items open","Three action items still open"],"examples":[["Standup","Action items open from yesterday retro."]],"alternatives":[],"notes":[],"pronunciation":"ak-shun ai-temz","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'daily-standup'
  and lower(i.term) = lower('action items open');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-action-items-open',
  'phrase',
  'action items open',
  'Follow-ups from the meeting are still not done.',
  'Standup',
  'B1',
  'phr',
  '{"patterns":["Action items open","Three action items still open"],"examples":[["Standup","Action items open from yesterday retro."]],"alternatives":[],"notes":[],"pronunciation":"ak-shun ai-temz","countability":"na"}'::jsonb,
  1,
  1,
  8,
  true,
  true,
  8,
  'ak-shun ai-temz',
  'na'
from public.vocabulary_situations as s
where s.slug = 'daily-standup'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('action items open')
  );

-- daily-standup #9 hotfix
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 9,
  pronunciation = 'hot-fiks',
  countability = 'countable',
  type = 'word',
  meaning = 'A small production fix shipped outside the normal train.',
  context = 'Standup',
  level = 'A2',
  pos = 'n',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["ship a hotfix","the hotfix is soaking"],"examples":[["Standup","I shipped a hotfix for the timeout."]],"alternatives":[],"notes":[],"pronunciation":"hot-fiks","countability":"countable"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'daily-standup'
  and lower(i.term) = lower('hotfix');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-hotfix',
  'word',
  'hotfix',
  'A small production fix shipped outside the normal train.',
  'Standup',
  'A2',
  'n',
  '{"patterns":["ship a hotfix","the hotfix is soaking"],"examples":[["Standup","I shipped a hotfix for the timeout."]],"alternatives":[],"notes":[],"pronunciation":"hot-fiks","countability":"countable"}'::jsonb,
  1,
  1,
  9,
  true,
  true,
  9,
  'hot-fiks',
  'countable'
from public.vocabulary_situations as s
where s.slug = 'daily-standup'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('hotfix')
  );

-- daily-standup #10 customer impact
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 10,
  pronunciation = 'kus-tuh-mer im-pakt',
  countability = 'na',
  type = 'phrase',
  meaning = 'What users actually felt during an incident or delay.',
  context = 'Standup',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["customer impact is local","no customer impact"],"examples":[["Standup","Customer impact stayed local to checkout."]],"alternatives":[],"notes":[],"pronunciation":"kus-tuh-mer im-pakt","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'daily-standup'
  and lower(i.term) = lower('customer impact');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-customer-impact',
  'phrase',
  'customer impact',
  'What users actually felt during an incident or delay.',
  'Standup',
  'B1',
  'phr',
  '{"patterns":["customer impact is local","no customer impact"],"examples":[["Standup","Customer impact stayed local to checkout."]],"alternatives":[],"notes":[],"pronunciation":"kus-tuh-mer im-pakt","countability":"na"}'::jsonb,
  1,
  1,
  10,
  true,
  true,
  10,
  'kus-tuh-mer im-pakt',
  'na'
from public.vocabulary_situations as s
where s.slug = 'daily-standup'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('customer impact')
  );

-- meetings #1 action item
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 1,
  pronunciation = 'ak-shun ai-tem',
  countability = 'na',
  type = 'phrase',
  meaning = 'A named follow-up with an owner and a due time.',
  context = 'Meetings',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["capture an action item","action item for ..."],"examples":[["Meetings","Action item: Sam will file the RFC today."]],"alternatives":[],"notes":[],"pronunciation":"ak-shun ai-tem","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'meetings'
  and lower(i.term) = lower('action item');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-action-item',
  'phrase',
  'action item',
  'A named follow-up with an owner and a due time.',
  'Meetings',
  'A2',
  'phr',
  '{"patterns":["capture an action item","action item for ..."],"examples":[["Meetings","Action item: Sam will file the RFC today."]],"alternatives":[],"notes":[],"pronunciation":"ak-shun ai-tem","countability":"na"}'::jsonb,
  1,
  1,
  1,
  true,
  true,
  1,
  'ak-shun ai-tem',
  'na'
from public.vocabulary_situations as s
where s.slug = 'meetings'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('action item')
  );

-- meetings #2 recap
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 2,
  pronunciation = 'ree-kap',
  countability = 'countable',
  type = 'word',
  meaning = 'A short summary of decisions and next steps.',
  context = 'Meetings',
  level = 'A2',
  pos = 'n',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["quick recap","I will send a recap"],"examples":[["Meetings","Quick recap: we keep the flag off overnight."]],"alternatives":[],"notes":[],"pronunciation":"ree-kap","countability":"countable"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'meetings'
  and lower(i.term) = lower('recap');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-recap',
  'word',
  'recap',
  'A short summary of decisions and next steps.',
  'Meetings',
  'A2',
  'n',
  '{"patterns":["quick recap","I will send a recap"],"examples":[["Meetings","Quick recap: we keep the flag off overnight."]],"alternatives":[],"notes":[],"pronunciation":"ree-kap","countability":"countable"}'::jsonb,
  1,
  1,
  2,
  true,
  true,
  2,
  'ree-kap',
  'countable'
from public.vocabulary_situations as s
where s.slug = 'meetings'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('recap')
  );

-- meetings #3 align on scope
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 3,
  pronunciation = 'uh-lain on skohp',
  countability = 'na',
  type = 'phrase',
  meaning = 'Agree what is in and out of the work before you continue.',
  context = 'Meetings',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Let''s align on scope","We still need to align on scope"],"examples":[["Meetings","Let''s align on scope before we estimate."]],"alternatives":[],"notes":[],"pronunciation":"uh-lain on skohp","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'meetings'
  and lower(i.term) = lower('align on scope');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-align-on-scope',
  'phrase',
  'align on scope',
  'Agree what is in and out of the work before you continue.',
  'Meetings',
  'B1',
  'phr',
  '{"patterns":["Let''s align on scope","We still need to align on scope"],"examples":[["Meetings","Let''s align on scope before we estimate."]],"alternatives":[],"notes":[],"pronunciation":"uh-lain on skohp","countability":"na"}'::jsonb,
  1,
  1,
  3,
  true,
  true,
  3,
  'uh-lain on skohp',
  'na'
from public.vocabulary_situations as s
where s.slug = 'meetings'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('align on scope')
  );

-- meetings #4 park that topic
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 4,
  pronunciation = 'park that top-ik',
  countability = 'na',
  type = 'phrase',
  meaning = 'Stop discussing it now and return later so the meeting can finish.',
  context = 'Meetings',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Let''s park that topic","Park that for the parking lot"],"examples":[["Meetings","Let''s park that topic and finish the decision."]],"alternatives":[],"notes":[],"pronunciation":"park that top-ik","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'meetings'
  and lower(i.term) = lower('park that topic');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-park-that-topic',
  'phrase',
  'park that topic',
  'Stop discussing it now and return later so the meeting can finish.',
  'Meetings',
  'B1',
  'phr',
  '{"patterns":["Let''s park that topic","Park that for the parking lot"],"examples":[["Meetings","Let''s park that topic and finish the decision."]],"alternatives":[],"notes":[],"pronunciation":"park that top-ik","countability":"na"}'::jsonb,
  1,
  1,
  4,
  true,
  true,
  4,
  'park that top-ik',
  'na'
from public.vocabulary_situations as s
where s.slug = 'meetings'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('park that topic')
  );

-- meetings #5 decision owner
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 5,
  pronunciation = 'di-si-zhun oh-ner',
  countability = 'na',
  type = 'phrase',
  meaning = 'The person who must make or record the call.',
  context = 'Meetings',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Who is the decision owner?","decision owner is ..."],"examples":[["Meetings","Decision owner is Priya for the cutover window."]],"alternatives":[],"notes":[],"pronunciation":"di-si-zhun oh-ner","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'meetings'
  and lower(i.term) = lower('decision owner');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-decision-owner',
  'phrase',
  'decision owner',
  'The person who must make or record the call.',
  'Meetings',
  'B1',
  'phr',
  '{"patterns":["Who is the decision owner?","decision owner is ..."],"examples":[["Meetings","Decision owner is Priya for the cutover window."]],"alternatives":[],"notes":[],"pronunciation":"di-si-zhun oh-ner","countability":"na"}'::jsonb,
  1,
  1,
  5,
  true,
  true,
  5,
  'di-si-zhun oh-ner',
  'na'
from public.vocabulary_situations as s
where s.slug = 'meetings'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('decision owner')
  );

-- meetings #6 hard-stop
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 6,
  pronunciation = 'hard stop',
  countability = 'na',
  type = 'phrase',
  meaning = 'The time the meeting must end, even if items remain.',
  context = 'Meetings',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["We have a hard-stop at ...","hard-stop in five minutes"],"examples":[["Meetings","Hard-stop at 16:00; remaining items go async."]],"alternatives":[],"notes":[],"pronunciation":"hard stop","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'meetings'
  and lower(i.term) = lower('hard-stop');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-hard-stop',
  'phrase',
  'hard-stop',
  'The time the meeting must end, even if items remain.',
  'Meetings',
  'B1',
  'phr',
  '{"patterns":["We have a hard-stop at ...","hard-stop in five minutes"],"examples":[["Meetings","Hard-stop at 16:00; remaining items go async."]],"alternatives":[],"notes":[],"pronunciation":"hard stop","countability":"na"}'::jsonb,
  1,
  1,
  6,
  true,
  true,
  6,
  'hard stop',
  'na'
from public.vocabulary_situations as s
where s.slug = 'meetings'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('hard-stop')
  );

-- meetings #7 pre-read
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 7,
  pronunciation = 'pree-reed',
  countability = 'na',
  type = 'phrase',
  meaning = 'Material people should read before the meeting.',
  context = 'Meetings',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Please read the pre-read","pre-read is in the doc"],"examples":[["Meetings","The RFC is the pre-read for this review."]],"alternatives":[],"notes":[],"pronunciation":"pree-reed","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'meetings'
  and lower(i.term) = lower('pre-read');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-pre-read',
  'phrase',
  'pre-read',
  'Material people should read before the meeting.',
  'Meetings',
  'B1',
  'phr',
  '{"patterns":["Please read the pre-read","pre-read is in the doc"],"examples":[["Meetings","The RFC is the pre-read for this review."]],"alternatives":[],"notes":[],"pronunciation":"pree-reed","countability":"na"}'::jsonb,
  1,
  1,
  7,
  true,
  true,
  7,
  'pree-reed',
  'na'
from public.vocabulary_situations as s
where s.slug = 'meetings'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('pre-read')
  );

-- meetings #8 working agreements
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 8,
  pronunciation = 'wur-king uh-gree-ments',
  countability = 'na',
  type = 'phrase',
  meaning = 'Team rules for how you run meetings and make decisions.',
  context = 'Meetings',
  level = 'B2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["our working agreements","update the working agreements"],"examples":[["Meetings","Working agreements: cameras optional, decisions in writing."]],"alternatives":[],"notes":[],"pronunciation":"wur-king uh-gree-ments","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'meetings'
  and lower(i.term) = lower('working agreements');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-working-agreements',
  'phrase',
  'working agreements',
  'Team rules for how you run meetings and make decisions.',
  'Meetings',
  'B2',
  'phr',
  '{"patterns":["our working agreements","update the working agreements"],"examples":[["Meetings","Working agreements: cameras optional, decisions in writing."]],"alternatives":[],"notes":[],"pronunciation":"wur-king uh-gree-ments","countability":"na"}'::jsonb,
  1,
  1,
  8,
  true,
  true,
  8,
  'wur-king uh-gree-ments',
  'na'
from public.vocabulary_situations as s
where s.slug = 'meetings'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('working agreements')
  );

-- meetings #9 timebox overrun
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 9,
  pronunciation = 'taim-boks oh-ver-run',
  countability = 'na',
  type = 'phrase',
  meaning = 'The agenda slot ran past the minutes you reserved.',
  context = 'Meetings',
  level = 'B2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["timebox overrun on ...","avoid another timebox overrun"],"examples":[["Meetings","Timebox overrun on estimates; park the rest."]],"alternatives":[],"notes":[],"pronunciation":"taim-boks oh-ver-run","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'meetings'
  and lower(i.term) = lower('timebox overrun');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-timebox-overrun',
  'phrase',
  'timebox overrun',
  'The agenda slot ran past the minutes you reserved.',
  'Meetings',
  'B2',
  'phr',
  '{"patterns":["timebox overrun on ...","avoid another timebox overrun"],"examples":[["Meetings","Timebox overrun on estimates; park the rest."]],"alternatives":[],"notes":[],"pronunciation":"taim-boks oh-ver-run","countability":"na"}'::jsonb,
  1,
  1,
  9,
  true,
  true,
  9,
  'taim-boks oh-ver-run',
  'na'
from public.vocabulary_situations as s
where s.slug = 'meetings'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('timebox overrun')
  );

-- meetings #10 decision required
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 10,
  pronunciation = 'di-si-zhun ri-kwai-erd',
  countability = 'na',
  type = 'phrase',
  meaning = 'The meeting cannot close until someone makes a call.',
  context = 'Meetings',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Decision required on ...","this is decision required"],"examples":[["Meetings","Decision required: ship behind a flag or wait."]],"alternatives":[],"notes":[],"pronunciation":"di-si-zhun ri-kwai-erd","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'meetings'
  and lower(i.term) = lower('decision required');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-decision-required',
  'phrase',
  'decision required',
  'The meeting cannot close until someone makes a call.',
  'Meetings',
  'B1',
  'phr',
  '{"patterns":["Decision required on ...","this is decision required"],"examples":[["Meetings","Decision required: ship behind a flag or wait."]],"alternatives":[],"notes":[],"pronunciation":"di-si-zhun ri-kwai-erd","countability":"na"}'::jsonb,
  1,
  1,
  10,
  true,
  true,
  10,
  'di-si-zhun ri-kwai-erd',
  'na'
from public.vocabulary_situations as s
where s.slug = 'meetings'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('decision required')
  );

-- task-progress #1 take ownership
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 1,
  pronunciation = 'teik oh-ner-ship',
  countability = 'na',
  type = 'phrase',
  meaning = 'Become the owner and drive the ticket to done.',
  context = 'Ticket',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["I''ll take ownership of ...","take ownership of this ticket"],"examples":[["Ticket","I''ll take ownership of this ticket."]],"alternatives":[],"notes":[],"pronunciation":"teik oh-ner-ship","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'task-progress'
  and lower(i.term) = lower('take ownership');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-take-ownership',
  'phrase',
  'take ownership',
  'Become the owner and drive the ticket to done.',
  'Ticket',
  'A2',
  'phr',
  '{"patterns":["I''ll take ownership of ...","take ownership of this ticket"],"examples":[["Ticket","I''ll take ownership of this ticket."]],"alternatives":[],"notes":[],"pronunciation":"teik oh-ner-ship","countability":"na"}'::jsonb,
  1,
  1,
  1,
  true,
  true,
  1,
  'teik oh-ner-ship',
  'na'
from public.vocabulary_situations as s
where s.slug = 'task-progress'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('take ownership')
  );

-- task-progress #2 address review comments
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 2,
  pronunciation = 'uh-dres ri-vyoo',
  countability = 'na',
  type = 'phrase',
  meaning = 'Handle PR feedback in a named window.',
  context = 'PR',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["I''ll address the review comments ...","address review comments today"],"examples":[["PR","I''ll address the review comments this afternoon."]],"alternatives":[],"notes":[],"pronunciation":"uh-dres ri-vyoo","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'task-progress'
  and lower(i.term) = lower('address review comments');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-address-review-comments',
  'phrase',
  'address review comments',
  'Handle PR feedback in a named window.',
  'PR',
  'B1',
  'phr',
  '{"patterns":["I''ll address the review comments ...","address review comments today"],"examples":[["PR","I''ll address the review comments this afternoon."]],"alternatives":[],"notes":[],"pronunciation":"uh-dres ri-vyoo","countability":"na"}'::jsonb,
  1,
  1,
  2,
  true,
  true,
  2,
  'uh-dres ri-vyoo',
  'na'
from public.vocabulary_situations as s
where s.slug = 'task-progress'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('address review comments')
  );

-- task-progress #3 unblock the pipeline
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 3,
  pronunciation = 'un-blok the pai-plain',
  countability = 'na',
  type = 'phrase',
  meaning = 'Restore CI or the deploy path, usually before end of day.',
  context = 'CI',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["I''ll unblock the pipeline ...","unblock the pipeline before EOD"],"examples":[["CI","I''ll unblock the pipeline before EOD."]],"alternatives":[],"notes":[],"pronunciation":"un-blok the pai-plain","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'task-progress'
  and lower(i.term) = lower('unblock the pipeline');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-unblock-the-pipeline',
  'phrase',
  'unblock the pipeline',
  'Restore CI or the deploy path, usually before end of day.',
  'CI',
  'B1',
  'phr',
  '{"patterns":["I''ll unblock the pipeline ...","unblock the pipeline before EOD"],"examples":[["CI","I''ll unblock the pipeline before EOD."]],"alternatives":[],"notes":[],"pronunciation":"un-blok the pai-plain","countability":"na"}'::jsonb,
  1,
  1,
  3,
  true,
  true,
  3,
  'un-blok the pai-plain',
  'na'
from public.vocabulary_situations as s
where s.slug = 'task-progress'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('unblock the pipeline')
  );

-- task-progress #4 blocked on review
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 4,
  pronunciation = 'blokt on ri-vyoo',
  countability = 'na',
  type = 'phrase',
  meaning = 'The ticket waits on a reviewer, not on more coding.',
  context = 'PR',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["I am blocked on review","blocked on review for ..."],"examples":[["PR","This ticket is blocked on review."]],"alternatives":[],"notes":[],"pronunciation":"blokt on ri-vyoo","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'task-progress'
  and lower(i.term) = lower('blocked on review');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-blocked-on-review',
  'phrase',
  'blocked on review',
  'The ticket waits on a reviewer, not on more coding.',
  'PR',
  'A2',
  'phr',
  '{"patterns":["I am blocked on review","blocked on review for ..."],"examples":[["PR","This ticket is blocked on review."]],"alternatives":[],"notes":[],"pronunciation":"blokt on ri-vyoo","countability":"na"}'::jsonb,
  1,
  1,
  4,
  true,
  true,
  4,
  'blokt on ri-vyoo',
  'na'
from public.vocabulary_situations as s
where s.slug = 'task-progress'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('blocked on review')
  );

-- task-progress #5 blocked on access
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 5,
  pronunciation = 'blokt on ak-ses',
  countability = 'na',
  type = 'phrase',
  meaning = 'You cannot continue until permissions or credentials arrive.',
  context = 'Ticket',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["blocked on access to ..."],"examples":[["Ticket","I am blocked on access to staging logs."]],"alternatives":[],"notes":[],"pronunciation":"blokt on ak-ses","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'task-progress'
  and lower(i.term) = lower('blocked on access');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-blocked-on-access',
  'phrase',
  'blocked on access',
  'You cannot continue until permissions or credentials arrive.',
  'Ticket',
  'A2',
  'phr',
  '{"patterns":["blocked on access to ..."],"examples":[["Ticket","I am blocked on access to staging logs."]],"alternatives":[],"notes":[],"pronunciation":"blokt on ak-ses","countability":"na"}'::jsonb,
  1,
  1,
  5,
  true,
  true,
  5,
  'blokt on ak-ses',
  'na'
from public.vocabulary_situations as s
where s.slug = 'task-progress'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('blocked on access')
  );

-- task-progress #6 blocked on dependency
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 6,
  pronunciation = 'blokt on di-pen-den-see',
  countability = 'na',
  type = 'phrase',
  meaning = 'Another team or ticket must land first.',
  context = 'Ticket',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["blocked on a dependency","blocked on dependency X"],"examples":[["Ticket","We are blocked on a dependency in billing."]],"alternatives":[],"notes":[],"pronunciation":"blokt on di-pen-den-see","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'task-progress'
  and lower(i.term) = lower('blocked on dependency');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-blocked-on-dependency',
  'phrase',
  'blocked on dependency',
  'Another team or ticket must land first.',
  'Ticket',
  'B1',
  'phr',
  '{"patterns":["blocked on a dependency","blocked on dependency X"],"examples":[["Ticket","We are blocked on a dependency in billing."]],"alternatives":[],"notes":[],"pronunciation":"blokt on di-pen-den-see","countability":"na"}'::jsonb,
  1,
  1,
  6,
  true,
  true,
  6,
  'blokt on di-pen-den-see',
  'na'
from public.vocabulary_situations as s
where s.slug = 'task-progress'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('blocked on dependency')
  );

-- task-progress #7 ship behind a flag
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 7,
  pronunciation = 'ship bi-haind uh flag',
  countability = 'na',
  type = 'phrase',
  meaning = 'Merge to prod with the change off until you turn it on.',
  context = 'Deploy',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Let''s ship behind a flag","shipped behind a flag"],"examples":[["Deploy","We will ship behind a flag and soak overnight."]],"alternatives":[],"notes":[],"pronunciation":"ship bi-haind uh flag","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'task-progress'
  and lower(i.term) = lower('ship behind a flag');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-ship-behind-a-flag',
  'phrase',
  'ship behind a flag',
  'Merge to prod with the change off until you turn it on.',
  'Deploy',
  'B1',
  'phr',
  '{"patterns":["Let''s ship behind a flag","shipped behind a flag"],"examples":[["Deploy","We will ship behind a flag and soak overnight."]],"alternatives":[],"notes":[],"pronunciation":"ship bi-haind uh flag","countability":"na"}'::jsonb,
  1,
  1,
  7,
  true,
  true,
  7,
  'ship bi-haind uh flag',
  'na'
from public.vocabulary_situations as s
where s.slug = 'task-progress'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('ship behind a flag')
  );

-- task-progress #8 ship the hotfix
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 8,
  pronunciation = 'ship the hot-fiks',
  countability = 'na',
  type = 'phrase',
  meaning = 'Send the emergency fix to production.',
  context = 'Deploy',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["ship the hotfix","ready to ship the hotfix"],"examples":[["Deploy","CI is green; ship the hotfix."]],"alternatives":[],"notes":[],"pronunciation":"ship the hot-fiks","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'task-progress'
  and lower(i.term) = lower('ship the hotfix');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-ship-the-hotfix',
  'phrase',
  'ship the hotfix',
  'Send the emergency fix to production.',
  'Deploy',
  'A2',
  'phr',
  '{"patterns":["ship the hotfix","ready to ship the hotfix"],"examples":[["Deploy","CI is green; ship the hotfix."]],"alternatives":[],"notes":[],"pronunciation":"ship the hot-fiks","countability":"na"}'::jsonb,
  1,
  1,
  8,
  true,
  true,
  8,
  'ship the hot-fiks',
  'na'
from public.vocabulary_situations as s
where s.slug = 'task-progress'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('ship the hotfix')
  );

-- task-progress #9 align on next steps
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 9,
  pronunciation = 'uh-lain on next steps',
  countability = 'na',
  type = 'phrase',
  meaning = 'Agree who does what after this update.',
  context = 'Ticket',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Let''s align on next steps","need to align on next steps"],"examples":[["Ticket","Let''s align on next steps before we split the work."]],"alternatives":[],"notes":[],"pronunciation":"uh-lain on next steps","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'task-progress'
  and lower(i.term) = lower('align on next steps');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-align-on-next-steps',
  'phrase',
  'align on next steps',
  'Agree who does what after this update.',
  'Ticket',
  'B1',
  'phr',
  '{"patterns":["Let''s align on next steps","need to align on next steps"],"examples":[["Ticket","Let''s align on next steps before we split the work."]],"alternatives":[],"notes":[],"pronunciation":"uh-lain on next steps","countability":"na"}'::jsonb,
  1,
  1,
  9,
  true,
  true,
  9,
  'uh-lain on next steps',
  'na'
from public.vocabulary_situations as s
where s.slug = 'task-progress'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('align on next steps')
  );

-- task-progress #10 convert the spike
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 10,
  pronunciation = 'kon-vert the spaik',
  countability = 'na',
  type = 'phrase',
  meaning = 'Turn research into concrete tickets the team can pick up.',
  context = 'Ticket',
  level = 'B2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["convert the spike into tickets","I''ll convert the spike into ..."],"examples":[["Ticket","I''ll convert the spike into implementation tickets."]],"alternatives":[],"notes":[],"pronunciation":"kon-vert the spaik","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'task-progress'
  and lower(i.term) = lower('convert the spike');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-convert-the-spike',
  'phrase',
  'convert the spike',
  'Turn research into concrete tickets the team can pick up.',
  'Ticket',
  'B2',
  'phr',
  '{"patterns":["convert the spike into tickets","I''ll convert the spike into ..."],"examples":[["Ticket","I''ll convert the spike into implementation tickets."]],"alternatives":[],"notes":[],"pronunciation":"kon-vert the spaik","countability":"na"}'::jsonb,
  1,
  1,
  10,
  true,
  true,
  10,
  'kon-vert the spaik',
  'na'
from public.vocabulary_situations as s
where s.slug = 'task-progress'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('convert the spike')
  );

-- bugs-problems #1 reproduce the bug
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 1,
  pronunciation = 'ree-pruh-doos',
  countability = 'na',
  type = 'phrase',
  meaning = 'Make the failure happen again on purpose so you can fix it.',
  context = 'Incident',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["I can reproduce the bug","cannot reproduce the bug"],"examples":[["Incident","I can reproduce the bug on staging with that payload."]],"alternatives":[],"notes":[],"pronunciation":"ree-pruh-doos","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'bugs-problems'
  and lower(i.term) = lower('reproduce the bug');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-reproduce-the-bug',
  'phrase',
  'reproduce the bug',
  'Make the failure happen again on purpose so you can fix it.',
  'Incident',
  'A2',
  'phr',
  '{"patterns":["I can reproduce the bug","cannot reproduce the bug"],"examples":[["Incident","I can reproduce the bug on staging with that payload."]],"alternatives":[],"notes":[],"pronunciation":"ree-pruh-doos","countability":"na"}'::jsonb,
  1,
  1,
  1,
  true,
  true,
  1,
  'ree-pruh-doos',
  'na'
from public.vocabulary_situations as s
where s.slug = 'bugs-problems'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('reproduce the bug')
  );

-- bugs-problems #2 reproduce on staging
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 2,
  pronunciation = 'ree-pruh-doos on stei-jing',
  countability = 'na',
  type = 'phrase',
  meaning = 'Confirm the bug in the staging environment, not only in prod.',
  context = 'QA',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["Can you reproduce on staging?","reproduced on staging"],"examples":[["QA","We reproduced on staging after the last deploy."]],"alternatives":[],"notes":[],"pronunciation":"ree-pruh-doos on stei-jing","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'bugs-problems'
  and lower(i.term) = lower('reproduce on staging');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-reproduce-on-staging',
  'phrase',
  'reproduce on staging',
  'Confirm the bug in the staging environment, not only in prod.',
  'QA',
  'B1',
  'phr',
  '{"patterns":["Can you reproduce on staging?","reproduced on staging"],"examples":[["QA","We reproduced on staging after the last deploy."]],"alternatives":[],"notes":[],"pronunciation":"ree-pruh-doos on stei-jing","countability":"na"}'::jsonb,
  1,
  1,
  2,
  true,
  true,
  2,
  'ree-pruh-doos on stei-jing',
  'na'
from public.vocabulary_situations as s
where s.slug = 'bugs-problems'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('reproduce on staging')
  );

-- bugs-problems #3 reproduce in production read-only
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 3,
  pronunciation = 'ree-pruh-doos in pruh-duk-shun',
  countability = 'na',
  type = 'phrase',
  meaning = 'Inspect prod without writes when staging cannot show the bug.',
  context = 'Incident',
  level = 'B2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["reproduce in production read-only"],"examples":[["Incident","We will reproduce in production read-only with tracing on."]],"alternatives":[],"notes":[],"pronunciation":"ree-pruh-doos in pruh-duk-shun","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'bugs-problems'
  and lower(i.term) = lower('reproduce in production read-only');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-reproduce-in-production-read-only',
  'phrase',
  'reproduce in production read-only',
  'Inspect prod without writes when staging cannot show the bug.',
  'Incident',
  'B2',
  'phr',
  '{"patterns":["reproduce in production read-only"],"examples":[["Incident","We will reproduce in production read-only with tracing on."]],"alternatives":[],"notes":[],"pronunciation":"ree-pruh-doos in pruh-duk-shun","countability":"na"}'::jsonb,
  1,
  1,
  3,
  true,
  true,
  3,
  'ree-pruh-doos in pruh-duk-shun',
  'na'
from public.vocabulary_situations as s
where s.slug = 'bugs-problems'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('reproduce in production read-only')
  );

-- bugs-problems #4 page the secondary
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 4,
  pronunciation = 'peij the sek-un-de-ree',
  countability = 'na',
  type = 'phrase',
  meaning = 'Call the backup on-call when impact or uncertainty is high.',
  context = 'On-call',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["page the secondary","I paged the secondary"],"examples":[["On-call","P0 checkout; page the secondary."]],"alternatives":[],"notes":[],"pronunciation":"peij the sek-un-de-ree","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'bugs-problems'
  and lower(i.term) = lower('page the secondary');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-page-the-secondary',
  'phrase',
  'page the secondary',
  'Call the backup on-call when impact or uncertainty is high.',
  'On-call',
  'B1',
  'phr',
  '{"patterns":["page the secondary","I paged the secondary"],"examples":[["On-call","P0 checkout; page the secondary."]],"alternatives":[],"notes":[],"pronunciation":"peij the sek-un-de-ree","countability":"na"}'::jsonb,
  1,
  1,
  4,
  true,
  true,
  4,
  'peij the sek-un-de-ree',
  'na'
from public.vocabulary_situations as s
where s.slug = 'bugs-problems'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('page the secondary')
  );

-- bugs-problems #5 ship a forward fix
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 5,
  pronunciation = 'ship uh for-werd fiks',
  countability = 'na',
  type = 'phrase',
  meaning = 'Fix forward instead of rolling back, when rollback is worse.',
  context = 'Incident',
  level = 'B2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["ship a forward fix","we will ship a forward fix"],"examples":[["Incident","Rollback is unsafe here; ship a forward fix."]],"alternatives":[],"notes":[],"pronunciation":"ship uh for-werd fiks","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'bugs-problems'
  and lower(i.term) = lower('ship a forward fix');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-ship-a-forward-fix',
  'phrase',
  'ship a forward fix',
  'Fix forward instead of rolling back, when rollback is worse.',
  'Incident',
  'B2',
  'phr',
  '{"patterns":["ship a forward fix","we will ship a forward fix"],"examples":[["Incident","Rollback is unsafe here; ship a forward fix."]],"alternatives":[],"notes":[],"pronunciation":"ship uh for-werd fiks","countability":"na"}'::jsonb,
  1,
  1,
  5,
  true,
  true,
  5,
  'ship uh for-werd fiks',
  'na'
from public.vocabulary_situations as s
where s.slug = 'bugs-problems'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('ship a forward fix')
  );

-- bugs-problems #6 page only on burn
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 6,
  pronunciation = 'peij ohn-lee on burn',
  countability = 'na',
  type = 'phrase',
  meaning = 'Alert humans only when error budget or SLO burn is real.',
  context = 'Alert',
  level = 'C1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["page only on burn","this alert should page only on burn"],"examples":[["Alert","Tune this monitor to page only on burn."]],"alternatives":[],"notes":[],"pronunciation":"peij ohn-lee on burn","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'bugs-problems'
  and lower(i.term) = lower('page only on burn');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-page-only-on-burn',
  'phrase',
  'page only on burn',
  'Alert humans only when error budget or SLO burn is real.',
  'Alert',
  'C1',
  'phr',
  '{"patterns":["page only on burn","this alert should page only on burn"],"examples":[["Alert","Tune this monitor to page only on burn."]],"alternatives":[],"notes":[],"pronunciation":"peij ohn-lee on burn","countability":"na"}'::jsonb,
  1,
  1,
  6,
  true,
  true,
  6,
  'peij ohn-lee on burn',
  'na'
from public.vocabulary_situations as s
where s.slug = 'bugs-problems'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('page only on burn')
  );

-- bugs-problems #7 page the SME
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 7,
  pronunciation = 'peij the es-em-ee',
  countability = 'na',
  type = 'phrase',
  meaning = 'Bring in the subject-matter expert for this system.',
  context = 'On-call',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["page the SME for ..."],"examples":[["On-call","This is a Postgres lock; page the SME."]],"alternatives":[],"notes":[],"pronunciation":"peij the es-em-ee","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'bugs-problems'
  and lower(i.term) = lower('page the SME');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-page-the-sme',
  'phrase',
  'page the SME',
  'Bring in the subject-matter expert for this system.',
  'On-call',
  'B1',
  'phr',
  '{"patterns":["page the SME for ..."],"examples":[["On-call","This is a Postgres lock; page the SME."]],"alternatives":[],"notes":[],"pronunciation":"peij the es-em-ee","countability":"na"}'::jsonb,
  1,
  1,
  7,
  true,
  true,
  7,
  'peij the es-em-ee',
  'na'
from public.vocabulary_situations as s
where s.slug = 'bugs-problems'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('page the SME')
  );

-- bugs-problems #8 degraded mode
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 8,
  pronunciation = 'di-grei-did mohd',
  countability = 'na',
  type = 'phrase',
  meaning = 'The system still runs with reduced features during an incident.',
  context = 'Incident',
  level = 'B2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["run in degraded mode","stay in degraded mode"],"examples":[["Incident","Checkout is in degraded mode with payments cached."]],"alternatives":[],"notes":[],"pronunciation":"di-grei-did mohd","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'bugs-problems'
  and lower(i.term) = lower('degraded mode');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-degraded-mode',
  'phrase',
  'degraded mode',
  'The system still runs with reduced features during an incident.',
  'Incident',
  'B2',
  'phr',
  '{"patterns":["run in degraded mode","stay in degraded mode"],"examples":[["Incident","Checkout is in degraded mode with payments cached."]],"alternatives":[],"notes":[],"pronunciation":"di-grei-did mohd","countability":"na"}'::jsonb,
  1,
  1,
  8,
  true,
  true,
  8,
  'di-grei-did mohd',
  'na'
from public.vocabulary_situations as s
where s.slug = 'bugs-problems'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('degraded mode')
  );

-- bugs-problems #9 postmortem
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 9,
  pronunciation = 'pohst-mor-tem',
  countability = 'countable',
  type = 'word',
  meaning = 'A blameless write-up of what failed and what you will change.',
  context = 'Postmortem',
  level = 'B1',
  pos = 'n',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["write the postmortem","postmortem is due ..."],"examples":[["Postmortem","I will draft the postmortem after the soak."]],"alternatives":[],"notes":[],"pronunciation":"pohst-mor-tem","countability":"countable"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'bugs-problems'
  and lower(i.term) = lower('postmortem');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-postmortem',
  'word',
  'postmortem',
  'A blameless write-up of what failed and what you will change.',
  'Postmortem',
  'B1',
  'n',
  '{"patterns":["write the postmortem","postmortem is due ..."],"examples":[["Postmortem","I will draft the postmortem after the soak."]],"alternatives":[],"notes":[],"pronunciation":"pohst-mor-tem","countability":"countable"}'::jsonb,
  1,
  1,
  9,
  true,
  true,
  9,
  'pohst-mor-tem',
  'countable'
from public.vocabulary_situations as s
where s.slug = 'bugs-problems'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('postmortem')
  );

-- bugs-problems #10 P0
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 10,
  pronunciation = 'pee-zeer-oh',
  countability = 'countable',
  type = 'word',
  meaning = 'Highest severity: drop other work and treat as an incident.',
  context = 'Incident',
  level = 'A2',
  pos = 'n',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["this is a P0","declare P0"],"examples":[["Incident","Checkout is down; this is a P0."]],"alternatives":[],"notes":[],"pronunciation":"pee-zeer-oh","countability":"countable"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'bugs-problems'
  and lower(i.term) = lower('P0');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-p0',
  'word',
  'P0',
  'Highest severity: drop other work and treat as an incident.',
  'Incident',
  'A2',
  'n',
  '{"patterns":["this is a P0","declare P0"],"examples":[["Incident","Checkout is down; this is a P0."]],"alternatives":[],"notes":[],"pronunciation":"pee-zeer-oh","countability":"countable"}'::jsonb,
  1,
  1,
  10,
  true,
  true,
  10,
  'pee-zeer-oh',
  'countable'
from public.vocabulary_situations as s
where s.slug = 'bugs-problems'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('P0')
  );

-- client-communication #1 as discussed
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 1,
  pronunciation = 'az dis-kust',
  countability = 'na',
  type = 'phrase',
  meaning = 'Point back to an earlier agreement without repeating the whole thread.',
  context = 'Client',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["As discussed, ...","as discussed on the call"],"examples":[["Client","As discussed, we will keep the workaround overnight."]],"alternatives":[],"notes":[],"pronunciation":"az dis-kust","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'client-communication'
  and lower(i.term) = lower('as discussed');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-as-discussed',
  'phrase',
  'as discussed',
  'Point back to an earlier agreement without repeating the whole thread.',
  'Client',
  'B1',
  'phr',
  '{"patterns":["As discussed, ...","as discussed on the call"],"examples":[["Client","As discussed, we will keep the workaround overnight."]],"alternatives":[],"notes":[],"pronunciation":"az dis-kust","countability":"na"}'::jsonb,
  1,
  1,
  1,
  true,
  true,
  1,
  'az dis-kust',
  'na'
from public.vocabulary_situations as s
where s.slug = 'client-communication'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('as discussed')
  );

-- client-communication #2 follow-up
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 2,
  pronunciation = 'fol-oh-up',
  countability = 'countable',
  type = 'word',
  meaning = 'A later message or meeting that continues the same thread.',
  context = 'Client',
  level = 'A2',
  pos = 'n',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["send a follow-up","a short follow-up"],"examples":[["Client","I will send a follow-up with owners and times."]],"alternatives":[],"notes":[],"pronunciation":"fol-oh-up","countability":"countable"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'client-communication'
  and lower(i.term) = lower('follow-up');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-follow-up',
  'word',
  'follow-up',
  'A later message or meeting that continues the same thread.',
  'Client',
  'A2',
  'n',
  '{"patterns":["send a follow-up","a short follow-up"],"examples":[["Client","I will send a follow-up with owners and times."]],"alternatives":[],"notes":[],"pronunciation":"fol-oh-up","countability":"countable"}'::jsonb,
  1,
  1,
  2,
  true,
  true,
  2,
  'fol-oh-up',
  'countable'
from public.vocabulary_situations as s
where s.slug = 'client-communication'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('follow-up')
  );

-- client-communication #3 follow-up email
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 3,
  pronunciation = 'fol-oh-up ee-meil',
  countability = 'na',
  type = 'phrase',
  meaning = 'The written recap you send after a client call.',
  context = 'Client',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["send a follow-up email","the follow-up email covers ..."],"examples":[["Client","The follow-up email lists owners and due dates."]],"alternatives":[],"notes":[],"pronunciation":"fol-oh-up ee-meil","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'client-communication'
  and lower(i.term) = lower('follow-up email');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-follow-up-email',
  'phrase',
  'follow-up email',
  'The written recap you send after a client call.',
  'Client',
  'A2',
  'phr',
  '{"patterns":["send a follow-up email","the follow-up email covers ..."],"examples":[["Client","The follow-up email lists owners and due dates."]],"alternatives":[],"notes":[],"pronunciation":"fol-oh-up ee-meil","countability":"na"}'::jsonb,
  1,
  1,
  3,
  true,
  true,
  3,
  'fol-oh-up ee-meil',
  'na'
from public.vocabulary_situations as s
where s.slug = 'client-communication'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('follow-up email')
  );

-- client-communication #4 next steps
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 4,
  pronunciation = 'next steps',
  countability = 'na',
  type = 'phrase',
  meaning = 'The concrete actions after this update.',
  context = 'Client',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["next steps are ...","here are the next steps"],"examples":[["Client","Next steps: we soak until 16:00, then confirm."]],"alternatives":[],"notes":[],"pronunciation":"next steps","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'client-communication'
  and lower(i.term) = lower('next steps');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-next-steps',
  'phrase',
  'next steps',
  'The concrete actions after this update.',
  'Client',
  'A2',
  'phr',
  '{"patterns":["next steps are ...","here are the next steps"],"examples":[["Client","Next steps: we soak until 16:00, then confirm."]],"alternatives":[],"notes":[],"pronunciation":"next steps","countability":"na"}'::jsonb,
  1,
  1,
  4,
  true,
  true,
  4,
  'next steps',
  'na'
from public.vocabulary_situations as s
where s.slug = 'client-communication'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('next steps')
  );

-- client-communication #5 owners and due dates
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 5,
  pronunciation = 'oh-nerz and doo deits',
  countability = 'na',
  type = 'phrase',
  meaning = 'Name who does what by when in a client recap.',
  context = 'Client',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["follow-up with owners and due dates","owners and due dates in the recap"],"examples":[["Client","I''ll send a follow-up with owners and due dates."]],"alternatives":[],"notes":[],"pronunciation":"oh-nerz and doo deits","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'client-communication'
  and lower(i.term) = lower('owners and due dates');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-owners-and-due-dates',
  'phrase',
  'owners and due dates',
  'Name who does what by when in a client recap.',
  'Client',
  'B1',
  'phr',
  '{"patterns":["follow-up with owners and due dates","owners and due dates in the recap"],"examples":[["Client","I''ll send a follow-up with owners and due dates."]],"alternatives":[],"notes":[],"pronunciation":"oh-nerz and doo deits","countability":"na"}'::jsonb,
  1,
  1,
  5,
  true,
  true,
  5,
  'oh-nerz and doo deits',
  'na'
from public.vocabulary_situations as s
where s.slug = 'client-communication'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('owners and due dates')
  );

-- client-communication #6 workaround steps
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 6,
  pronunciation = 'wurk-uh-round steps',
  countability = 'na',
  type = 'phrase',
  meaning = 'The numbered actions a client can take until the fix lands.',
  context = 'Client',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["here are the workaround steps","workaround steps in the doc"],"examples":[["Client","Workaround steps are in the status update."]],"alternatives":[],"notes":[],"pronunciation":"wurk-uh-round steps","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'client-communication'
  and lower(i.term) = lower('workaround steps');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-workaround-steps',
  'phrase',
  'workaround steps',
  'The numbered actions a client can take until the fix lands.',
  'Client',
  'B1',
  'phr',
  '{"patterns":["here are the workaround steps","workaround steps in the doc"],"examples":[["Client","Workaround steps are in the status update."]],"alternatives":[],"notes":[],"pronunciation":"wurk-uh-round steps","countability":"na"}'::jsonb,
  1,
  1,
  6,
  true,
  true,
  6,
  'wurk-uh-round steps',
  'na'
from public.vocabulary_situations as s
where s.slug = 'client-communication'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('workaround steps')
  );

-- client-communication #7 alignment meeting
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 7,
  pronunciation = 'uh-lain-ment mee-ting',
  countability = 'na',
  type = 'phrase',
  meaning = 'A call whose job is to agree scope, dates, or owners.',
  context = 'Client',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["book an alignment meeting","short alignment meeting"],"examples":[["Client","Let''s book a short alignment meeting on the new ETA."]],"alternatives":[],"notes":[],"pronunciation":"uh-lain-ment mee-ting","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'client-communication'
  and lower(i.term) = lower('alignment meeting');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-alignment-meeting',
  'phrase',
  'alignment meeting',
  'A call whose job is to agree scope, dates, or owners.',
  'Client',
  'B1',
  'phr',
  '{"patterns":["book an alignment meeting","short alignment meeting"],"examples":[["Client","Let''s book a short alignment meeting on the new ETA."]],"alternatives":[],"notes":[],"pronunciation":"uh-lain-ment mee-ting","countability":"na"}'::jsonb,
  1,
  1,
  7,
  true,
  true,
  7,
  'uh-lain-ment mee-ting',
  'na'
from public.vocabulary_situations as s
where s.slug = 'client-communication'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('alignment meeting')
  );

-- client-communication #8 blocked on client
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 8,
  pronunciation = 'blokt on klai-ent',
  countability = 'na',
  type = 'phrase',
  meaning = 'You cannot continue until the client sends info or access.',
  context = 'Client',
  level = 'B1',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["We are blocked on client for ..."],"examples":[["Client","We are blocked on client for a failing request id."]],"alternatives":[],"notes":[],"pronunciation":"blokt on klai-ent","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'client-communication'
  and lower(i.term) = lower('blocked on client');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-blocked-on-client',
  'phrase',
  'blocked on client',
  'You cannot continue until the client sends info or access.',
  'Client',
  'B1',
  'phr',
  '{"patterns":["We are blocked on client for ..."],"examples":[["Client","We are blocked on client for a failing request id."]],"alternatives":[],"notes":[],"pronunciation":"blokt on klai-ent","countability":"na"}'::jsonb,
  1,
  1,
  8,
  true,
  true,
  8,
  'blokt on klai-ent',
  'na'
from public.vocabulary_situations as s
where s.slug = 'client-communication'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('blocked on client')
  );

-- client-communication #9 status update
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 9,
  pronunciation = 'sta-tus up-deit',
  countability = 'na',
  type = 'phrase',
  meaning = 'A short current picture of impact, actions, and next check-in.',
  context = 'Client',
  level = 'A2',
  pos = 'phr',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["send a status update","status update at ..."],"examples":[["Client","Status update at 16:00: workaround holding, patch soaking."]],"alternatives":[],"notes":[],"pronunciation":"sta-tus up-deit","countability":"na"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'client-communication'
  and lower(i.term) = lower('status update');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-status-update',
  'phrase',
  'status update',
  'A short current picture of impact, actions, and next check-in.',
  'Client',
  'A2',
  'phr',
  '{"patterns":["send a status update","status update at ..."],"examples":[["Client","Status update at 16:00: workaround holding, patch soaking."]],"alternatives":[],"notes":[],"pronunciation":"sta-tus up-deit","countability":"na"}'::jsonb,
  1,
  1,
  9,
  true,
  true,
  9,
  'sta-tus up-deit',
  'na'
from public.vocabulary_situations as s
where s.slug = 'client-communication'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('status update')
  );

-- client-communication #10 timeline
update public.vocabulary_items as i
set
  is_core = true,
  core_order = 10,
  pronunciation = 'taim-lain',
  countability = 'countable',
  type = 'word',
  meaning = 'The sequence of what happened and what happens next.',
  context = 'Client',
  level = 'A2',
  pos = 'n',
  content = coalesce(i.content, '{}'::jsonb) || '{"patterns":["share the timeline","here is the timeline"],"examples":[["Client","Here is the timeline from detect to mitigate."]],"alternatives":[],"notes":[],"pronunciation":"taim-lain","countability":"countable"}'::jsonb,
  updated_at = now()
from public.vocabulary_situations as s
where i.situation_id = s.id
  and s.slug = 'client-communication'
  and lower(i.term) = lower('timeline');

insert into public.vocabulary_items (
  situation_id, item_key, type, term, meaning, context, level, pos, content,
  content_schema_version, content_revision, sort_order, published,
  is_core, core_order, pronunciation, countability
)
select
  s.id,
  'core-timeline',
  'word',
  'timeline',
  'The sequence of what happened and what happens next.',
  'Client',
  'A2',
  'n',
  '{"patterns":["share the timeline","here is the timeline"],"examples":[["Client","Here is the timeline from detect to mitigate."]],"alternatives":[],"notes":[],"pronunciation":"taim-lain","countability":"countable"}'::jsonb,
  1,
  1,
  10,
  true,
  true,
  10,
  'taim-lain',
  'countable'
from public.vocabulary_situations as s
where s.slug = 'client-communication'
  and not exists (
    select 1
    from public.vocabulary_items as i
    where i.situation_id = s.id
      and lower(i.term) = lower('timeline')
  );

do $$
declare
  v_count integer;
begin
  select count(*) into v_count
  from public.vocabulary_items
  where is_core = true and published = true;
  if v_count <> 50 then
    raise exception 'Expected 50 core vocabulary items, found %', v_count;
  end if;
end
$$;

commit;
